unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Ordered__c.field-meta.xml
<CustomField>
    <fullName>Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/PurchaseOrderLineItemTriggerHandler.cls
public with sharing class PurchaseOrderLineItemTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    
    public PurchaseOrderLineItemTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
        
    public void OnBeforeInsert(PurchaseOrderLineItem__c[] newPurchaseOrderLineItems){
            
        Set<Id> PurchaseOrderIds = new Set<Id>();    

        for (PurchaseOrderLineItem__c poLI : newPurchaseOrderLineItems) {
            if (poLI.PurchaseOrder__c != null) {
                PurchaseOrderIds.add(poLI.PurchaseOrder__c);
            }
        }
        
        Map<Id, PurchaseOrder__c> PurchaseOrders = new Map<Id, PurchaseOrder__c>(
            [SELECT Id, CurrencyIsoCode from PurchaseOrder__c WHERE Id IN :PurchaseOrderIds]
        );
        
        for(PurchaseOrderLineItem__c poLI : newPurchaseOrderLineItems){
            PurchaseOrder__c po = PurchaseOrders.get(poLI.PurchaseOrder__c);

            if(po != null && po.CurrencyIsoCode != poLi.CurrencyIsoCode){
                poLi.CurrencyIsoCode = po.CurrencyIsoCode;
            }
        }

    }
    
    public void OnAfterInsert(PurchaseOrderLineItem__c[] newPurchaseOrderLineItems){

    }
    
    //@future public static void OnAfterInsertAsync(Set<ID> newPurchaseOrderLineItemIDs){
    //}
    
    public void OnBeforeUpdate(PurchaseOrderLineItem__c[] oldPurchaseOrderLineItems, PurchaseOrderLineItem__c[] updatedPurchaseOrderLineItems, Map<ID, PurchaseOrderLineItem__c> purchaseOrderLineItemMap){

    }
    
    public void OnAfterUpdate(PurchaseOrderLineItem__c[] oldPurchaseOrderLineItems, PurchaseOrderLineItem__c[] updatedPurchaseOrderLineItems, Map<ID, PurchaseOrderLineItem__c> purchaseOrderLineItemMap){
    
    }
    
    //@future public static void OnAfterUpdateAsync(Set<ID> updatedPurchaseOrderLineItemIDs){
    //}
    
    public void OnBeforeDelete(PurchaseOrderLineItem__c[] purchaseOrderLineItemsToDelete, Map<ID, PurchaseOrderLineItem__c> purchaseOrderLineItemMap){
    
        Set<Id> PurchaseOrderIds = new Set<Id>();    

        for (PurchaseOrderLineItem__c poLI : purchaseOrderLineItemsToDelete) {
            if (poLI.PurchaseOrder__c != null) {
                PurchaseOrderIds.add(poLI.PurchaseOrder__c);
            }
        }
        
        Map<Id, PurchaseOrder__c> PurchaseOrders = new Map<Id, PurchaseOrder__c>(
            [SELECT Id, Ordered__c from PurchaseOrder__c WHERE Id IN :PurchaseOrderIds]
        );
        
        for(PurchaseOrderLineItem__c poLI : purchaseOrderLineItemsToDelete){
            PurchaseOrder__c po = PurchaseOrders.get(poLI.PurchaseOrder__c);

            if(po != null && po.Ordered__c){
                poLI.addError('Cannot delete a Line Item from an Purchase Order that has been Ordered.');
            }
        }
        
    }
    
    public void OnAfterDelete(PurchaseOrderLineItem__c[] deletedPurchaseOrderLineItems, Map<ID, PurchaseOrderLineItem__c> purchaseOrderLineItemMap){
        
    }
    
    //@future public static void OnAfterDeleteAsync(Set<ID> deletedPurchaseOrderLineItemIDs){
    //}
    
    public void OnUndelete(PurchaseOrderLineItem__c[] restoredPurchaseOrderLineItems){
    
        Set<Id> PurchaseOrderIds = new Set<Id>();    

        for (PurchaseOrderLineItem__c poLI : restoredPurchaseOrderLineItems) {
            if (poLI.PurchaseOrder__c != null) {
                PurchaseOrderIds.add(poLI.PurchaseOrder__c);
            }
        }
        
        Map<Id, PurchaseOrder__c> PurchaseOrders = new Map<Id, PurchaseOrder__c>(
            [SELECT Id, Ordered__c from PurchaseOrder__c WHERE Id IN :PurchaseOrderIds]
        );
        
        for(PurchaseOrderLineItem__c poLI : restoredPurchaseOrderLineItems){
            PurchaseOrder__c po = PurchaseOrders.get(poLI.PurchaseOrder__c);

            if(po != null && po.Ordered__c){
                poLI.addError('Cannot undelete a Line Item from an Purchase Order that has been Ordered.');
            }
        }
        
    }
    
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
    
    public boolean IsVisualforcePageContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsWebServiceContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsExecuteAnonymousContext{
        get{ return !IsTriggerContext;}
    }
}