unpackaged/main/default/objects/Account/fields/ActiveSiteAccounts__c.field-meta.xml
<CustomField>
    <fullName>ActiveSiteAccounts__c</fullName>
    <description>Field to count number of active site accounts related to the parent account.</description>
    <inlineHelpText>Number of related active site accounts.</inlineHelpText>
    <label>Active Site Accounts</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Has_subscription__c.field-meta.xml
<CustomField>
    <fullName>Has_subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The user will check this checkbox if this account has a subscription to EnerjyHUB.</description>
    <label>Active in enerjyhub</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vendor_Master_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Master_Code__c</fullName>
    <externalId>true</externalId>
    <label>Vendor Master Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/numberOfSiteAccounts.cls
Public class numberOfSiteAccounts{
    
    
    public static void rollUpSiteAccounts(list<Account> newacclist, Map<id, Account> oldAccMap){
        
        Set<Id> Ids= new Set<Id>();
        Set<Id> oldIds = new Set<Id>();
        
        for(Account acc: newacclist){
            if(oldAccMap != null){
            if( acc.ParentId!=null && acc.ParentId != oldAccMap.get(acc.id).ParentId){
                Ids.add(oldAccMap.get(acc.Id).ParentId);
            }
        }
            if(acc.ParentId!=null)
                Ids.add(acc.ParentId);
        	}
        
        if (!Ids.isEmpty()) {
            
            List<Account> AccountToUpdate = new List<Account>();
            
            for (AggregateResult ar : [SELECT COUNT(ID),Parentid FROM Account 
                                       WHERE  Parent.Vendor_Master_Code__c != NULL AND Has_subscription__c = true
                                       AND Parent.ActiveSiteAccounts__c != 0 AND ParentID IN :Ids GROUP BY ParentID ]) {
                                           
                                           system.debug('ar@@'+ar);
                                           Id accID = (ID)ar.get('ParentID');
                                           Integer count = (Integer)ar.get('expr0');
                                           Account acc1 = new Account(Id=accID);
                                           acc1.ActiveSiteAccounts__c = count;
                                           AccountToUpdate.add(acc1);
                                       }
            
            
            
            if (!AccountToUpdate.isEmpty()) {
                update AccountToUpdate;
            }    
        } 
    }
    
    public static void rollUpExisitngAccounts(list<account> oldacclist){
        
        Set<Id> Ids= new Set<Id>();
        
        
        for(Account acc: oldacclist){
            
            if(acc.ParentId!=null || acc.Id != NULL)
                Ids.add(acc.ParentId);
        }
        
        if (!Ids.isEmpty()) {
            List<Account> AccountToUpdate = new List<Account>();
            
            for (AggregateResult ar : [SELECT COUNT(ID),Parentid FROM Account 
                                       WHERE  Parent.Vendor_Master_Code__c != NULL AND Has_subscription__c = true
                                       AND ActiveSiteAccounts__c != 0 AND ParentID IN :Ids GROUP BY ParentID ]) {
                                           
                                           Id accID = (ID)ar.get('ParentID');
                                           Integer count = (Integer)ar.get('expr0');
                                           Account acc1 = new Account(Id=accID);
                                           acc1.ActiveSiteAccounts__c = count;
                                           AccountToUpdate.add(acc1);
                              }
                        
            if (!AccountToUpdate.isEmpty()) {
                try{
                    update AccountToUpdate;
                }
                catch(exception e){
                    
                }
            }
        }
    }
}