unpackaged/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this business a supplier of an OEM or other organisation?</inlineHelpText>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Buy_Price__c.field-meta.xml
<CustomField>
    <fullName>Buy_Price__c</fullName>
    <label>Buy Price</label>
    <summarizedField>OpportunityLineItem.Buy_Price__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Subscription__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Buy_Price__c.field-meta.xml
<CustomField>
    <fullName>Buy_Price__c</fullName>
    <inlineHelpText>The amount the product costs for Majenta. (List price less discount).</inlineHelpText>
    <label>Buy Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Category__c)</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contract_No_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_No_Site_ID__c</fullName>
    <label>Contract No/Site ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>Finish_Date__c</fullName>
    <formula>Contract_Length_Months__c + Current_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finish Date (Legacy)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/FinishDate__c.field-meta.xml
<CustomField>
    <fullName>FinishDate__c</fullName>
    <label>Finish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>PricebookEntry.Product2.Supplier__r.Name</formula>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3Dconnexion</fullName>
            </value>
            <value>
                <fullName>3DSystems</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>AGS</fullName>
            </value>
            <value>
                <fullName>aPriori</fullName>
            </value>
            <value>
                <fullName>Autodesk</fullName>
            </value>
            <value>
                <fullName>AutoTrack</fullName>
            </value>
            <value>
                <fullName>Bakbone</fullName>
            </value>
            <value>
                <fullName>C3P</fullName>
            </value>
            <value>
                <fullName>Chaos Group</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Citrix</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Elysium</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>Icona</fullName>
            </value>
            <value>
                <fullName>JLR</fullName>
            </value>
            <value>
                <fullName>KnowledgePoint</fullName>
            </value>
            <value>
                <fullName>Majenta</fullName>
            </value>
            <value>
                <fullName>Mentor Graphics</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>MX</fullName>
            </value>
            <value>
                <fullName>NetApp</fullName>
            </value>
            <value>
                <fullName>NETGEAR</fullName>
            </value>
            <value>
                <fullName>Overland</fullName>
            </value>
            <value>
                <fullName>QNAP</fullName>
            </value>
            <value>
                <fullName>Quadrispace</fullName>
            </value>
            <value>
                <fullName>Rolls-Royce</fullName>
            </value>
            <value>
                <fullName>Siemens</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Account is not Type Supplier.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier, Majenta Supplier</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>contains</operation>
            <value>Jaguar</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>SupplierProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>OpportunityPurchaseOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipTo__c.field-meta.xml
<CustomField>
    <fullName>ShipTo__c</fullName>
    <label>Ship To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Majenta</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ShipTo__c</field>
            <operation>equals</operation>
            <valueField>Account.Type</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>PurchaseOrderShippingAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipToContact__c.field-meta.xml
<CustomField>
    <fullName>ShipToContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ShipToAccount__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>PurchaseOrderShippingContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Selected Account is not a Supplier.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
    <relationshipName>PurchaseOrdersSupplier</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0.2</defaultValue>
    <label>VAT Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FinishDate__c.field-meta.xml
<CustomField>
    <fullName>FinishDate__c</fullName>
    <label>Finish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GenerateOpportunityPurchaseOrder.cls
global class GenerateOpportunityPurchaseOrder {

public class Test_Exception extends Exception{}

    public static String[] generatePurchaseOrder(String OppId, String SuppId) {
    
        List<String> message = new List<String>();
        if(OppId!=null && SuppID!=null) {
            
            //Conversion currency map
            Map<String,Double> CurrencyConversionRate_Map = new Map<String,Double>();
            for (CurrencyType CT:[select Id,ConversionRate,IsoCode from CurrencyType]) {
                CurrencyConversionRate_Map.put(CT.IsoCode,CT.ConversionRate);
            }
            // Current Opportunity Record
            Opportunity Opp = [SELECT o.Id,
                                      o.CurrencyIsoCode,
                                      o.Account.Id 
                                      FROM Opportunity o WHERE o.Id=:OppId];
                                                 
            if(Opp!=null) {
                String productName;
                try{
                    // mapping between opportunity and new po
                    PurchaseOrder__c newPurchaseOrder = new PurchaseOrder__c( Opportunity__c = Opp.Id,
                                                            Date__c = System.Date.today(),
                                                            CurrencyIsoCode = Opp.CurrencyIsoCode,
                                                            Supplier__c = SuppId,
                                                            ShipTo__c = 'Customer',
                                                            ShipToAccount__c = Opp.Account.Id
                                                            );
                                                            
                    // Opportunity Primary Contact
                    List<OpportunityContactRole> Con = [SELECT ContactId FROM OpportunityContactRole WHERE OpportunityId=:OppId AND IsPrimary=true LIMIT 1];
                    if(Con.size()>0) newPurchaseOrder.ShipToContact__c = Con[0].ContactId;
                        
                    insert newPurchaseOrder;
                    
                    // List of Opportunity Line Item records associated to the current Opportunity record and selected Supplier
                    List<OpportunityLineItem> oProductList = new List<OpportunityLineItem>([SELECT p.PricebookEntryId,
                                                                                                   p.PricebookEntry.Product2.Id,
                                                                                                   p.PricebookEntry.Product2.Name,
                                                                                                   p.PricebookEntry.Product2.Description,
                                                                                                   p.PricebookEntry.Product2.Category__c,
                                                                                                   p.Description, 
                                                                                                   p.Quantity, 
                                                                                                   p.Buy_Price__c,
                                                                                                   p.Finish_Date__c,
                                                                                                   p.StartDate__c,
                                                                                                   p.FinishDate__c,
                                                                                                   p.Contract_No_Site_ID__c FROM OpportunityLineItem p 
                                                                                                   WHERE p.OpportunityId =:Opp.Id AND p.PricebookEntry.Product2.Supplier__c =:SuppId]);
                   
                   if(!oProductList.isEmpty()) { 
                     
                     Map<Id,Id> priceBookEntryList = new Map<Id,Id>();
                     Set<Id> setProductId = new Set<Id>();
                     for(OpportunityLineItem oProduct:oProductList) {
                        setProductId.add(oProduct.PricebookEntryId);
                     }
                     if(!setProductId.isEmpty()) {

                         List<PurchaseOrderLineItem__c> newPurchaseOrderLineItemList = new List<PurchaseOrderLineItem__c>();
                         for(OpportunityLineItem oProduct:oProductList) {
                                PurchaseOrderLineItem__c PurchaseOrderLineItem  = new  PurchaseOrderLineItem__c( 
                                                                                             PurchaseOrder__c = newPurchaseOrder.Id,
                                                                                             CurrencyIsoCode = newPurchaseOrder.CurrencyIsoCode 
                                                                                              );
                                if(PurchaseOrderLineItem.CurrencyIsoCode!='GBP') {
                                    PurchaseOrderLineItem.TaxRate__c = 0;
                                }
                                
                                //Convert UnitPrice into the Opportunity currency 
                                //Need to specify a Sales price
                                if(oProduct.Buy_Price__c!=null)                                                  
                                {   
                                    PurchaseOrderLineItem.UnitPrice__c =  (oProduct.Buy_Price__c / CurrencyConversionRate_Map.get(Opp.CurrencyIsoCode))*CurrencyConversionRate_Map.get(Opp.CurrencyIsoCode);
                                }
                                else{
                                    PurchaseOrderLineItem.UnitPrice__c = 1;
                                }
                                
                                // Quantity needs to be greater than 0
                                if(oProduct.Quantity!=null && oProduct.Quantity >0)                                                 
                                {   
                                    PurchaseOrderLineItem.Quantity__c =  oProduct.Quantity;
                                }
                                else{
                                    PurchaseOrderLineItem.Quantity__c = 1;
                                }
                                
                                //Name needs to contains more 1 characters
                                if(oProduct.PricebookEntry.Product2.Name!=null && oProduct.PricebookEntry.Product2.Name.length()>=2)                                                    
                                {   
                                    if(oProduct.PricebookEntry.Product2.Name.length()>80)
                                        PurchaseOrderLineItem.Name =  oProduct.PricebookEntry.Product2.Name.substring(0, 80);
                                    else
                                        PurchaseOrderLineItem.Name =  oProduct.PricebookEntry.Product2.Name;
                                }
                                else{
                                    PurchaseOrderLineItem.Name = 'Please complete the Name';
                                }
                                                                
                                //Description needs to contains more 4 characters
                                if(oProduct.Description!=null && oProduct.Description.length()>=5)                                                    
                                {   
                                    PurchaseOrderLineItem.Description__c =  oProduct.Description;
                                }
                                else if(oProduct.PricebookEntry.Product2.Description!=null){
                                    PurchaseOrderLineItem.Description__c =  oProduct.PricebookEntry.Product2.Description;
                                }
                                else{
                                    PurchaseOrderLineItem.Description__c = 'Please complete the Description';
                                }
                                                                
                                if(oProduct.StartDate__c!=null && oProduct.FinishDate__c!=null)
                                {
                                    PurchaseOrderLineItem.Description__c += '\n'+oProduct.StartDate__c.format()+' to '+oProduct.FinishDate__c.format();
                                }
                                
                                if(oProduct.Contract_No_Site_ID__c!=null)
                                {
                                    String cnsidDesc;
                                    if(oProduct.PricebookEntry.Product2.Category__c == 'Siemens'){
                                        cnsidDesc = 'Sold To';
                                    }else if(oProduct.PricebookEntry.Product2.Category__c == 'Autodesk'){
                                        cnsidDesc = 'Contract No.';
                                    }else{
                                        cnsidDesc = 'Contract No. / Sold To';
                                    }
                                    
                                    PurchaseOrderLineItem.Description__c += '\n'+cnsidDesc+': '+oProduct.Contract_No_Site_ID__c;
                                }
                                
                                                              
                                //System.debug('@@@@'+pBookEntryList);
                                if(oProduct.PricebookEntryId!=null)
                                {
                                    PurchaseOrderLineItem.Product__c = oProduct.PricebookEntry.Product2.Id;
                                    newPurchaseOrderLineItemList.add(PurchaseOrderLineItem);                                
                                }
                                                                
                                //Need a price book entry in order save an opportunity line item
                                productName = oProduct.PricebookEntry.Product2.Id;
                                
                                
                         }
                         if (!newPurchaseOrderLineItemList.isEmpty())
                                insert newPurchaseOrderLineItemList;
                     }
                     
                   }
                   
                    
                  message.add(newPurchaseOrder.Id);
                }   
                catch (Exception E) {
                    message.clear();
                    message.add('Purchase Order could not be generated!');
                    message.add(E.getMessage());
                }
            }
    
        }

        return message;
        
    }
    
    @isTest (seeAllData=true)
    public static void GenerateOpportunityPurchaseOrder()
    {
    
        //Insert Test Supplier Account
        Account suppAcc = new Account( Name = 'Test Supplier Account',
                                       Type = 'Supplier'
                                     );
        insert suppAcc;
        
        //Get the standard pricebook
        Pricebook2 Pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
        
        //Insert Test Product 1            
        Product2 prod1 = new Product2( Name = 'Test Product 1',
                                       Description = 'Test Product 1Description',
                                       Family = 'Test',
                                       ProductCode = 'TEST1',
                                       Supplier__c = suppAcc.Id
                                     );
        insert prod1;
        
        //Insert Test Product 1  Pricebook Entry
        PricebookEntry PbE1 = new PricebookEntry( Pricebook2Id = Pb.Id,
                                                  Product2Id = prod1.Id,
                                                  IsActive = TRUE,
                                                  UseStandardPrice= FALSE,
                                                  UnitPrice = 0.00
                                                );
        insert PbE1;

        User Usr = [Select id from User where Profile.Name ='Sales Support' and isActive = true limit 1];
        system.runAs(Usr){
        
            //Insert Test Account
            Account custAcc = new Account( Name = 'Test Account',
                                       Type = 'Customer',
                                       Phone = '01234567890'
                                     );
            insert custAcc;
            
            //Insert Test Opportunity
            Opportunity Opp = new Opportunity( Name = 'TestOpp',
                                               AccountId = custAcc.Id,
                                               Type = 'New Customer New Business',
                                               CloseDate = System.Date.today(),
                                               StageName = 'Order Received',
                                               Pricebook2Id = Pb.Id
                                             );
            insert Opp;
            
            //Insert Test Opportunity Line Item       
            OpportunityLineItem OppLi = new OpportunityLineItem( OpportunityId = Opp.Id,
                                                                 Quantity=1,
                                                                 TotalPrice = 1,
                                                                 PriceBookEntryId = PbE1.Id
                                                               );
            insert OppLi;
                                             
            generatePurchaseOrder(Opp.Id,suppAcc.Id);
            
        }
    }
    
}