unpackaged/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing)</relationshipLabel>
    <relationshipName>AccountBillingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/BillingAddress2__c.field-meta.xml
<CustomField>
    <fullName>BillingAddress2__c</fullName>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>ENERJYHUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/CustomerOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerOrderNumber__c</fullName>
    <externalId>true</externalId>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Shipping)</relationshipLabel>
    <relationshipName>AccountShippingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ShippingAddress2__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress2__c</fullName>
    <label>Shipping Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType2__c.field-meta.xml
<CustomField>
    <fullName>BusinessType2__c</fullName>
    <label>Business Type (Override)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>InvoiceLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CASE(Division__c,
"PLM", "PLM",
"Solid Edge", "PLM",
"COMOS", "PLM",
"MPLM Software Development", "PLM",
"enerjyhub","ENERJYHUB",
"SOLUTIONS"
)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Subscription__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/BusinessType2__c.field-meta.xml
<CustomField>
    <fullName>BusinessType2__c</fullName>
    <inlineHelpText>This is used to define the business type per product on mixed business deals.</inlineHelpText>
    <label>Business Type (Override)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Category__c)</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contract_No_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_No_Site_ID__c</fullName>
    <label>Contract No/Site ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>Finish_Date__c</fullName>
    <formula>Contract_Length_Months__c + Current_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finish Date (Legacy)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/FinishDate__c.field-meta.xml
<CustomField>
    <fullName>FinishDate__c</fullName>
    <label>Finish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3Dconnexion</fullName>
            </value>
            <value>
                <fullName>3DSystems</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>AGS</fullName>
            </value>
            <value>
                <fullName>aPriori</fullName>
            </value>
            <value>
                <fullName>Autodesk</fullName>
            </value>
            <value>
                <fullName>AutoTrack</fullName>
            </value>
            <value>
                <fullName>Bakbone</fullName>
            </value>
            <value>
                <fullName>C3P</fullName>
            </value>
            <value>
                <fullName>Chaos Group</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Citrix</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Elysium</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>Icona</fullName>
            </value>
            <value>
                <fullName>JLR</fullName>
            </value>
            <value>
                <fullName>KnowledgePoint</fullName>
            </value>
            <value>
                <fullName>Majenta</fullName>
            </value>
            <value>
                <fullName>Mentor Graphics</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>MX</fullName>
            </value>
            <value>
                <fullName>NetApp</fullName>
            </value>
            <value>
                <fullName>NETGEAR</fullName>
            </value>
            <value>
                <fullName>Overland</fullName>
            </value>
            <value>
                <fullName>QNAP</fullName>
            </value>
            <value>
                <fullName>Quadrispace</fullName>
            </value>
            <value>
                <fullName>Rolls-Royce</fullName>
            </value>
            <value>
                <fullName>Siemens</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FinishDate__c.field-meta.xml
<CustomField>
    <fullName>FinishDate__c</fullName>
    <label>Finish Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GenerateOpportunityInvoice.cls
global class GenerateOpportunityInvoice {

public class Test_Exception extends Exception{}
@AuraEnabled 
    WebService static String[] generateInvoice(String OppId)
    {
        List<String> message = new List<String>();
        if(OppId!=null)
        {
            
           //Conversion currency map
           Map<String,Double> CurrencyConversionRate_Map = new Map<String,Double>();
           for (CurrencyType CT:[select Id,ConversionRate,IsoCode from CurrencyType])
           {
                CurrencyConversionRate_Map.put(CT.IsoCode,CT.ConversionRate);
           }
            // Current Opportunity Record
            Opportunity Opp = [Select o.Id,
                                      o.Company__c,
                                      o.CurrencyIsoCode,
                                      o.Customer_Order_Number__c,
                                      o.Account.Id,
                                      o.Account.ShippingStreet,
                                      o.Account.ShippingCity,
                                      o.Account.ShippingState, 
                                      o.Account.ShippingPostalCode,
                                      o.Account.ShippingCountry,
                                      o.Account.BillingStreet,
                                      o.Account.BillingCity,
                                      o.Account.BillingState, 
                                      o.Account.BillingPostalCode,
                                      o.Account.BillingCountry
                                      From Opportunity o where o.Id=:OppId];
                                                 
            if(Opp!=null)    
            {
                String productName;
                try{
                    // mapping between opportunity and new invoice
                    Invoice__c newInvoice = new Invoice__c( Opportunity__c = Opp.Id,
                                                            Date__c = System.Date.today(),
                                                            Company__c = Opp.Company__c,
                                                            CustomerOrderNumber__c = Opp.Customer_Order_Number__c,
                                                            CurrencyIsoCode = Opp.CurrencyIsoCode
                                                            );
                                                            
                    //Set Bill To & Ship To Accounts as Opp Account
                    newInvoice.ShippingAccount__c = Opp.Account.Id;
                    newInvoice.BillingAccount__c = Opp.Account.Id;
                    
                    //Put the shipping address together in to a single string, no longer than 255 characters
                    String ShippingAddress ='';
                        if(Opp.Account.ShippingStreet != null)
                        {
                            ShippingAddress += Opp.Account.ShippingStreet;
                        }
                        if(Opp.Account.ShippingCity != null)
                        {
                            ShippingAddress += '\n' + Opp.Account.ShippingCity;
                        }
                        if(Opp.Account.ShippingState != null)
                        {
                            ShippingAddress += '\n' + Opp.Account.ShippingState;
                        }
                        if(Opp.Account.ShippingPostalCode != null)
                        {
                            ShippingAddress += '\n' + Opp.Account.ShippingPostalCode;
                        }
                        if(Opp.Account.ShippingCountry != null)
                        {
                            ShippingAddress += '\n' + Opp.Account.ShippingCountry;
                        }
                    if(ShippingAddress.length()>255)
                        newInvoice.ShippingAddress2__c = ShippingAddress.substring(0, 255);
                    else
                        newInvoice.ShippingAddress2__c = ShippingAddress;
                        
                    //Put the billing address together in to a single string, no longer than 255 characters
                    String BillingAddress ='';
                        if(Opp.Account.BillingStreet != null)
                        {
                            BillingAddress += Opp.Account.BillingStreet;
                        }
                        if(Opp.Account.BillingCity != null)
                        {
                            BillingAddress += '\n' + Opp.Account.BillingCity;
                        }
                        if(Opp.Account.BillingState != null)
                        {
                            BillingAddress += '\n' + Opp.Account.BillingState;
                        }
                        if(Opp.Account.BillingPostalCode != null)
                        {
                            BillingAddress += '\n' + Opp.Account.BillingPostalCode;
                        }
                        if(Opp.Account.BillingCountry != null)
                        {
                            BillingAddress += '\n' + Opp.Account.BillingCountry;
                        }
                    if(BillingAddress.length()>255)
                        newInvoice.BillingAddress2__c = BillingAddress.substring(0, 255);
                    else
                        newInvoice.BillingAddress2__c = BillingAddress;
                    
                    insert newInvoice;
                    
                    // List of support product records associated to the current support contract record
                    List<OpportunityLineItem> oProductList = new List<OpportunityLineItem>([SELECT p.PricebookEntryId,
                                                                                                   p.PricebookEntry.Product2.Id,
                                                                                                   p.PricebookEntry.Product2.Name,
                                                                                                   p.PricebookEntry.Product2.Description,
                                                                                                   p.PricebookEntry.Product2.Category__c,
                                                                                                   p.Description, 
                                                                                                   p.Quantity, 
                                                                                                   p.UnitPrice,
                                                                                                   p.Finish_Date__c,
                                                                                                   p.SortOrder,
                                                                                                   p.StartDate__c,
                                                                                                   p.FinishDate__c,
                                                                                                   p.Contract_No_Site_ID__c,
                                                                                                   p.BusinessType2__c 
                                                                                                   FROM OpportunityLineItem p 
                                                                                                   WHERE p.OpportunityId =:Opp.Id
                                                                                                   ORDER BY p.SortOrder]);
                   
                   if(!oProductList.isEmpty())
                   { 
                     
                     Map<Id,Id> priceBookEntryList = new Map<Id,Id>();
                     Set<Id> setProductId = new Set<Id>();
                     for(OpportunityLineItem oProduct:oProductList)
                     {
                        setProductId.add(oProduct.PricebookEntryId);
                     }
                     if(!setProductId.isEmpty())
                     {
                                                  
                                                                                                  
                         List<InvoiceLineItem__c> newInvoiceLineItemList = new List<InvoiceLineItem__c>();
                         for(OpportunityLineItem oProduct:oProductList)
                         {
                                InvoiceLineItem__c InvoiceLineItem  = new  InvoiceLineItem__c( 
                                                                                             Invoice__c = newInvoice.Id,
                                                                                             CurrencyIsoCode = newInvoice.CurrencyIsoCode,
                                                                                             SortOrder__c = oProduct.SortOrder, 
                                                                                             BusinessType2__c = oProduct.BusinessType2__c
                                                                                              );
                                if(InvoiceLineItem.CurrencyIsoCode!='GBP')
                                {
                                    InvoiceLineItem.TaxRate__c = 0;
                                }
                                
                                //Convert UnitPrice into the Opportunity currency 
                                //Need to specify a Sales price
                                if(oProduct.UnitPrice!=null)                                                  
                                {   
                                    InvoiceLineItem.UnitPrice__c =  (oProduct.UnitPrice / CurrencyConversionRate_Map.get(Opp.CurrencyIsoCode))*CurrencyConversionRate_Map.get(Opp.CurrencyIsoCode);
                                }
                                else{
                                    InvoiceLineItem.UnitPrice__c = 1;
                                }
                                
                                // Quantity needs to be greater than 0
                                if(oProduct.Quantity!=null && oProduct.Quantity >0)                                                 
                                {   
                                    InvoiceLineItem.Quantity__c =  oProduct.Quantity;
                                }
                                else{
                                    InvoiceLineItem.Quantity__c = 1;
                                }
                                
                                //Name needs to contains more 1 characters
                                if(oProduct.PricebookEntry.Product2.Name!=null && oProduct.PricebookEntry.Product2.Name.length()>=1)                                                    
                                {   
                                    if(oProduct.PricebookEntry.Product2.Name.length()>80)
                                        InvoiceLineItem.Name =  oProduct.PricebookEntry.Product2.Name.substring(0, 80);
                                    else
                                        InvoiceLineItem.Name =  oProduct.PricebookEntry.Product2.Name;
                                }
                                else{
                                    InvoiceLineItem.Name = 'Please complete the Name';
                                }
                                                                
                                //Description needs to contains more 5 characters
                                if(oProduct.Description!=null && oProduct.Description.length()>=5)                                                    
                                {   
                                    InvoiceLineItem.Description__c =  oProduct.Description;
                                }
                                else if(oProduct.PricebookEntry.Product2.Description!=null){
                                    InvoiceLineItem.Description__c =  oProduct.PricebookEntry.Product2.Description;
                                }
                                else{
                                    InvoiceLineItem.Description__c = 'Please complete the Description';
                                }
                                                                                                
                                if(oProduct.StartDate__c!=null && oProduct.FinishDate__c!=null)
                                {
                                    InvoiceLineItem.Description__c += '\n'+oProduct.StartDate__c.format()+' to '+oProduct.FinishDate__c.format();
                                }
                                
                                if(oProduct.Contract_No_Site_ID__c!=null)
                                {
                                    String cnsidDesc;
                                    if(oProduct.PricebookEntry.Product2.Category__c == 'Siemens'){
                                        cnsidDesc = 'Sold To';
                                    }else if(oProduct.PricebookEntry.Product2.Category__c == 'Autodesk'){
                                        cnsidDesc = 'Contract No.';
                                    }else{
                                        cnsidDesc = 'Contract No. / Sold To';
                                    }
                                    
                                    InvoiceLineItem.Description__c += '\n'+cnsidDesc+': '+oProduct.Contract_No_Site_ID__c;
                                }
                                                                                              
                                //System.debug('@@@@'+pBookEntryList);
                                if(oProduct.PricebookEntryId!=null)
                                {
                                    InvoiceLineItem.Product__c = oProduct.PricebookEntry.Product2.Id;
                                    newInvoiceLineItemList.add(InvoiceLineItem);                                
                                }
                                
                                
                                //Need a price book entry in order save an opportunity line item
                               
                                productName = oProduct.PricebookEntry.Product2.Id;
                                
                                
                         }
                         if (!newInvoiceLineItemList.isEmpty())
                                insert newInvoiceLineItemList;
                     }
                     
                   }
                   
                    
                  message.add(newInvoice.Id);
                }   
                catch (Exception E)
                {
                    message.clear();
                    message.add('Error');
                    message.add('Error on product '+productName +' '+E.getMessage());
                
                }
            }
    
        }

    return message;

    }
    
    @isTest (seeAllData=true)
    public static void GenerateOpportunityInvoice()
    {
            
        Pricebook2 Pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
                    
        Product2 P = new Product2( Name = 'Test Product',
                                   Description = 'Test Product Description',
                                   Family = 'Test',
                                   ProductCode = 'TEST1234'
                                  );
        insert P;
        
        PricebookEntry PbE = new PricebookEntry( Pricebook2Id = Pb.Id,
                                                 Product2Id = P.Id,
                                                 IsActive = TRUE,
                                                 UseStandardPrice= FALSE,
                                                 UnitPrice = 0.00
                                               );
        insert PbE;
            
        User Usr = [Select id from User where Profile.Name ='Sales Support' and isActive = true limit 1];
        system.runAs(Usr){
        
            //Insert Test Account
            Account Acc = new Account( Name = 'Test Account12345678',
                                       Type = 'Customer',
                                       Phone = '01234567890',
                                       ShippingStreet = 'Test Street',
                                       ShippingCity = 'Test City',
                                       ShippingState = 'Test State', 
                                       ShippingPostalCode = 'Test Postal Code',
                                       ShippingCountry = 'Test Country',
                                       BillingStreet = 'Test Street',
                                       BillingCity = 'Test City',
                                       BillingState = 'Test State',
                                       BillingPostalCode = 'Test Postal Code',
                                       BillingCountry = 'Test Country'
                                     );
            insert Acc;
            
            //Insert Test Opportunity
            Opportunity Opp = new Opportunity( Name = 'TestOpp',
                                               AccountId = Acc.Id,
                                               Type = 'New Customer New Business',
                                               CloseDate = System.Date.today(),
                                               StageName = 'Order Received',
                                               Pricebook2Id = Pb.Id
                                             );
            insert Opp;
            
            //Insert Test Opportunity Line Item       
            OpportunityLineItem OppLi = new OpportunityLineItem( OpportunityId = Opp.Id,
                                                                 Quantity=1,
                                                                 TotalPrice = 1,
                                                                 PriceBookEntryId = PbE.Id
                                                               );
            insert OppLi;
                                             
            GenerateOpportunityInvoice.generateInvoice(Opp.Id);
            
        }
    }


}