unpackaged/main/default/objects/Account/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this business a supplier of an OEM or other organisation?</inlineHelpText>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes (Billing)</relationshipLabel>
    <relationshipName>AccountBillingCreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/CreditNumber__c.field-meta.xml
<CustomField>
    <fullName>CreditNumber__c</fullName>
    <formula>Opportunity__r.Quote_Number_Revised__c+"-"+CompanyAbbr__c+"-"+Name</formula>
    <label>Credit Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing)</relationshipLabel>
    <relationshipName>AccountBillingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <formula>IF(LEFT(Name,3) == "INV",
  Opportunity__r.Quote_Number_Revised__c+"-"+Name,
  Opportunity__r.Quote_Number_Revised__c+"-"+CompanyAbbr__c+Name
)</formula>
    <label>Invoice Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Selected Account is not a Supplier.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
    <relationshipName>PurchaseOrdersSupplier</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/globalEmailPDF.cls
global class globalEmailPDF {
    @AuraEnabled
    WebService static void emailPDF(String recordId, String pageRef){
        
        String keyCode = recordId.subString(0,3);
        String objectName;
        
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        for(Schema.SObjectType objectInstance : gd.values()) {
            if(keyCode.equals(objectInstance.getDescribe().getKeyPrefix())) {
                objectName = objectInstance.getDescribe().getName();
            }
        }
        
        String docType;
        String docName;
        String docDesc;
        
        if( objectName == 'Invoice__c' ){
            Invoice__c inv = [SELECT Id, InvoiceNumber__c, BillingAccount__r.Name FROM Invoice__c WHERE Id =: recordId LIMIT 1 ];
            
            docType = 'Invoice';
            docName = inv.InvoiceNumber__c;
            docDesc = inv.BillingAccount__r.Name;
        } else if ( objectName == 'CreditNote__c' ){
            CreditNote__c crd = [SELECT Id, CreditNumber__c, BillingAccount__r.Name FROM CreditNote__c WHERE Id =: recordId LIMIT 1 ];
            
            docType = 'Credit Note';
            docName = crd.CreditNumber__c;
            docDesc = crd.BillingAccount__r.Name;
        } else if ( objectName == 'PurchaseOrder__c' ){    
            PurchaseOrder__c po = [SELECT Id, Name, Supplier__r.Name FROM PurchaseOrder__c WHERE Id =: recordId LIMIT 1 ];
            
            docType = 'Purchase Order';
            docName = po.Name;
            docDesc = po.Supplier__r.Name;
        }
    
        //PageReference pdf = new PageReference('/apex/InvoiceSingle');
        PageReference pdf = new PageReference(pageRef);
        pdf.getParameters().put('id', recordId);
        pdf.getParameters().put('headed', '1');
        
        Blob pdfBlob;
        
        try {
            pdfBlob = pdf.getContentAsPDF();
        } catch (VisualforceException e) {
            pdfBlob = Blob.valueOf('Some Text');
        }
    
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName(docName + '.pdf');
        attachment.setBody(pdfBlob);

        String[] toAddresses = new String[] {UserInfo.getUserEmail()};
        String subject =  docType + ' ' + docName + ' ' + docDesc;
        String body = 'Your requested copy ' + docType +' is attached.';
        
        email.setToAddresses(toAddresses);
        email.setSubject(subject);
        email.setPlainTextBody(body);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] {attachment});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email}); 
    }

}