unpackaged/main/default/objects/Account/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this business a supplier of an OEM or other organisation?</inlineHelpText>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Subscription__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>OpportunityPurchaseOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/OtherShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>OtherShippingAddress__c</fullName>
    <label>Other Shipping Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipTo__c.field-meta.xml
<CustomField>
    <fullName>ShipTo__c</fullName>
    <label>Ship To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Majenta</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ShipTo__c</field>
            <operation>equals</operation>
            <valueField>Account.Type</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>PurchaseOrderShippingAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/ShipToContact__c.field-meta.xml
<CustomField>
    <fullName>ShipToContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ShipToAccount__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>PurchaseOrderShippingContact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Selected Account is not a Supplier.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Supplier)</relationshipLabel>
    <relationshipName>PurchaseOrdersSupplier</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>0.2</defaultValue>
    <label>VAT Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/PurchaseOrderCloneWithItemsController.cls
public class PurchaseOrderCloneWithItemsController {
 
    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
     // add the instance for the variables being passed by id on the url
    private PurchaseOrder__c po {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}
 
    // initialize the controller
    public PurchaseOrderCloneWithItemsController(ApexPages.StandardController controller) {
 
        //initialize the stanrdard controller
        this.controller = controller;
        // load the current record
        po = (PurchaseOrder__c)controller.getRecord();
 
    }
 
    // method called from the VF's action attribute to clone the po
    public PageReference cloneWithItems() {
 
         // setup the save point for rollback
         Savepoint sp = Database.setSavepoint();
         PurchaseOrder__c newPO;
 
         try {
 
             //copy the purchase order - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
             po = [SELECT Id, Name, Opportunity__c, OtherShippingAddress__c, ShipTo__c, ShipToAccount__c, ShipToContact__c, Supplier__c  from PurchaseOrder__c WHERE Id = :po.id];
             po.Date__c = System.Date.today();
             newPO = po.clone(false);
             insert newPO;
 
             // set the id of the new po created for testing
               newRecordId = newPO.id;
 
             // copy over the line items - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
             List<PurchaseOrderLineItem__c> items = new List<PurchaseOrderLineItem__c>();
             for (PurchaseOrderLineItem__c pi : [SELECT Id, Name, Description__c, Product__c, Quantity__c, UnitPrice__c, TaxRate__c FROM PurchaseOrderLineItem__c p where PurchaseOrder__c = :po.id]) {
                  PurchaseOrderLineItem__c newPI = pi.clone(false);
                  newPI.PurchaseOrder__c = newPO.id;
                  items.add(newPI);
             }
             insert items;
 
         } catch (Exception e){
             // roll everything back in case of error
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
         }
 
        return new PageReference('/'+newPO.id+'/e?retURL=%2F'+newPO.id);
    }
    
    @isTest
    private static void testPOCloneController() {
 
       // setup a reference to the page the controller is expecting with the parameters
        PageReference pref = Page.PurchaseOrderClone;
        Test.setCurrentPage(pref);
 
        // setup a ship to account
        Account shipTo = new Account();
        shipTo.Name = 'PSAV 6FOO';
        shipTo.Type = 'Supplier';
        insert shipTo;
        
        //Insert Test Opportunity
        Opportunity Opp = new Opportunity( Name = 'TestOpp',
                                           CloseDate = System.Date.today(),
                                           StageName = 'Order Received'
                                         );
        insert Opp;
 
        // create new po record
        PurchaseOrder__c po = new PurchaseOrder__c();
        po.Opportunity__c = Opp.id;
        po.Date__c = Date.newInstance(2020,01,01);
        po.ShipTo__c = shipTo.id;
        insert po;
 
        // create a line item for the po
        PurchaseOrderLineItem__c pi1 = new PurchaseOrderLineItem__c();
        pi1.Description__c = 'My item';
        pi1.PurchaseOrder__c = po.id;
        pi1.Quantity__c = 1;
        pi1.UnitPrice__c = 10;
        insert pi1;
 
        // Construct the standard controller
        ApexPages.StandardController con = new ApexPages.StandardController(po);
 
        // create the controller
        PurchaseOrderCloneWithItemsController ext = new PurchaseOrderCloneWithItemsController(con);
 
        // Switch to test context
        Test.startTest();
 
        // call the cloneWithItems method
        PageReference ref = ext.cloneWithItems();
        // create the matching page reference
        PageReference redir = new PageReference('/'+ext.newRecordId+'/e?retURL=%2F'+ext.newRecordId);
 
        // make sure the user is sent to the correct url
        System.assertEquals(ref.getUrl(),redir.getUrl());
 
        // check that the new po was created successfully
        PurchaseOrder__c newPO = [select id from PurchaseOrder__c where id = :ext.newRecordId];
        System.assertNotEquals(newPO, null);
        // check that the line item was created
        List<PurchaseOrderLineItem__c> newItems = [Select p.Id From PurchaseOrderLineItem__c p where PurchaseOrder__c = :newPO.id];
        System.assertEquals(newItems.size(),1);
 
        // Switch back to runtime context
        Test.stopTest();
 
    }
  
}