unpackaged/main/default/objects/Account/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this business a supplier of an OEM or other organisation?</inlineHelpText>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(PricebookEntry.Product2.NewBusiness__c,
    "New",
    CASE( Opportunity.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type (Data)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>PricebookEntry.Product2.Supplier__r.Name</formula>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Account is not Type Supplier.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier, Majenta Supplier</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>contains</operation>
            <value>Jaguar</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>SupplierProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Expenses</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Overhead</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/GrossAmount__c.field-meta.xml
<CustomField>
    <fullName>GrossAmount__c</fullName>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/GrossMargin__c.field-meta.xml
<CustomField>
    <fullName>GrossMargin__c</fullName>
    <label>Gross Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Target__c/fields/MarginRecognised__c.field-meta.xml
<CustomField>
    <fullName>MarginRecognised__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New Margin Recognised</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/RevenueClosed__c.field-meta.xml
<CustomField>
    <fullName>RevenueClosed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New Revenue Closed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/RevenueRecognised__c.field-meta.xml
<CustomField>
    <fullName>RevenueRecognised__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New Revenue Recognised</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Sales Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TargetMethodTests.cls
@isTest(seeAllData=true)
public class TargetMethodTests {
    
    //These tests currently cover the following apex classes
    // * globalTargetMethods
    // * OpportunityTriggerHandler
    // * RevenueRecognisedTriggerHandler
    
    public static testmethod void testOpportunityTriggers(){
    
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
 
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = 'testuser@test123456789.com';
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = 'testuser@test123456789.com';
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'America/Mexico_City';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
        
        
        system.runAs(u){
        //Insert Test Supplier Account
        Account suppAcc = new Account( Name = 'Test Supplier Account',
                                       Type = 'Supplier'
                                     );
        insert suppAcc;
        
        //Get the standard pricebook
        Pricebook2 Pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
        
        //Insert Test Product 1            
        Product2 prod1 = new Product2( Name = 'Test Product 1',
                                       Description = 'Test Product 1 Description',
                                       Family = 'Test',
                                       ProductCode = 'TEST1',
                                       Supplier__c = suppAcc.Id
                                     );
        insert prod1;
        
        //Insert Test Product 1  Pricebook Entry
        PricebookEntry PbE1 = new PricebookEntry( Pricebook2Id = Pb.Id,
                                                  Product2Id = prod1.Id,
                                                  IsActive = TRUE,
                                                  UseStandardPrice= FALSE,
                                                  UnitPrice = 0.00
                                                );
        insert PbE1;
 
        
            Test.startTest();
            //Create a new Target
            Target__c t1 = new Target__c();
            t1.Name = 'Test Target';
            t1.Year__c = String.ValueOf(System.Today().Year());
            insert t1;
        
            //Test Opportunity on insert
            Opportunity opp1 = new Opportunity();
            opp1.Name = 'Test Opportunity #1';
            opp1.Type = 'New Customer New Business';
            opp1.StageName = 'Order In - Processed';
            opp1.Probability = 100;
            opp1.CloseDate = System.Today();
            opp1.Customer_Order_Number__c = '1234';
            //opp1.Amount = 1000;
            insert opp1;
            
            //Insert Test Opportunity Line Item       
            OpportunityLineItem opp1Li1 = new OpportunityLineItem();
            opp1Li1.OpportunityId = opp1.Id;
            opp1Li1.Quantity = 1;
            opp1Li1.TotalPrice = 1000;
            opp1Li1.PriceBookEntryId = PbE1.Id;
            insert opp1Li1;
            
            Opportunity opp1test1 = [SELECT Amount, Target__r.Id FROM Opportunity WHERE Id = :opp1.Id];
            Target__c t1Test1 = [SELECT Id, RevenueClosed__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(t1.Id, opp1test1.Target__r.Id); //check target was added
            system.assertEquals(opp1test1.Amount, t1Test1.RevenueClosed__c); //check opp1 amount was added to target
            
            //Insert some related Revenue__c records
            Revenue__c rev1 = new Revenue__c();
            rev1.Opportunity__c = opp1.Id;
            rev1.Type__c = 'SI';
            rev1.BusinessType__c = 'New';
            rev1.GrossAmount__c = 1000;
            rev1.GrossMargin__c = 1000;
            insert rev1;
            
            Target__c t1Test2 = [SELECT Id, RevenueRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(rev1.GrossAmount__c, t1Test2.RevenueRecognised__c); //check rev1 amount was added to target
            
            //Test Opportunity on update to remove from target
            Opportunity opp1update1 = [SELECT CloseDate FROM Opportunity WHERE Id = :opp1.Id];
            opp1update1.CloseDate = System.Today().AddYears(1); //add one year
            update opp1update1;
            
            Opportunity opp1test2 = [SELECT Target__c FROM Opportunity WHERE Id = :opp1.Id];
            Target__c t1Test3 = [SELECT Id, RevenueClosed__c, RevenueRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(TRUE, opp1test2.Target__c == null); //check target was removed
            system.assertEquals(0, t1Test3.RevenueClosed__c); //check opp1 amount was removed from target
            system.assertEquals(0, t1Test3.RevenueRecognised__c); //check rev1 amount was removed from target
            
            //Test Opportunity on update to add to target
            Opportunity opp1update2 = [SELECT CloseDate FROM Opportunity WHERE Id = :opp1.Id];
            opp1update2.CloseDate = System.Today();
            update opp1update2;
            
            Opportunity opp1test3 = [SELECT Amount, Target__r.Id FROM Opportunity WHERE Id = :opp1.Id];
            Target__c t1Test4 = [SELECT Id, RevenueClosed__c, RevenueRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(t1.Id, opp1test3.Target__r.Id); //check target was added
            system.assertEquals(opp1test3.Amount, t1Test4.RevenueClosed__c); //check opp1 amount was added from target
            system.assertEquals(rev1.GrossAmount__c, t1Test4.RevenueRecognised__c); //check rev1 amount was added from target
            
            //Test Opportunity on second insert
            Opportunity opp2 = new Opportunity();
            opp2.Name = 'Test Opportunity #2';
            opp2.Type = 'New Customer New Business';
            opp2.StageName = 'Order In - Processed';
            opp2.Probability = 100;
            opp2.CloseDate = System.Today();
            opp2.Customer_Order_Number__c = '1234';
            //opp2.Amount = 1000;
            insert opp2;
            
            //Insert Test Opportunity Line Item       
            OpportunityLineItem opp2Li1 = new OpportunityLineItem();
            opp2Li1.OpportunityId = opp2.Id;
            opp2Li1.Quantity = 1;
            opp2Li1.TotalPrice = 1000;
            opp2Li1.PriceBookEntryId = PbE1.Id;
            insert opp2Li1;
            
            Opportunity opp2test1 = [SELECT Target__r.Id FROM Opportunity WHERE Id = :opp2.Id];
            AggregateResult t1OppSum1 = [SELECT SUM(Amount) FROM Opportunity WHERE Target__c = :t1.Id];
            Target__c t1Test5 = [SELECT Id, RevenueRecognised__c, RevenueClosed__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(t1.Id, opp2test1.Target__r.Id); //check target was added
            system.assertEquals(t1Test5.RevenueClosed__c, t1OppSum1.get('expr0')); //check opp sum matches target value
            
            //Test Opportunity delete
            delete opp2;
            
            AggregateResult t1OppSum2 = [SELECT SUM(Amount) FROM Opportunity WHERE Target__c = :t1.Id];
            Target__c t1Test6 = [SELECT Id, RevenueRecognised__c, RevenueClosed__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(t1Test6.RevenueClosed__c, t1OppSum2.get('expr0')); //check opp sum matches target value
            
            //Test Opportunity undelete
            undelete opp2;
            
            AggregateResult t1OppSum3 = [SELECT SUM(Amount) FROM Opportunity WHERE Target__c = :t1.Id];
            Target__c t1Test7 = [SELECT Id, RevenueRecognised__c, RevenueClosed__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(t1Test7.RevenueClosed__c, t1OppSum3.get('expr0')); //check opp sum matches target value
            
            
            //Test Revenue__c on update
            Revenue__c rev1update1 = [SELECT GrossAmount__c, GrossMargin__c FROM Revenue__c WHERE Id = :rev1.Id];
            rev1update1.GrossAmount__c = 2000;
            rev1update1.GrossMargin__c = 2000;
            update rev1update1;
            
            Target__c t1Test8 = [SELECT RevenueRecognised__c, MarginRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(rev1update1.GrossAmount__c, t1Test8.RevenueRecognised__c); //check rev1 amount was updated on target
            system.assertEquals(rev1update1.GrossMargin__c, t1Test8.MarginRecognised__c); //check rev1 margin was updated on target
            
            //Test Revenue__c on delete
            delete rev1;
            
            Target__c t1Test9 = [SELECT RevenueRecognised__c, MarginRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(0, t1Test9.RevenueRecognised__c); //check rev1 amount was removed from target
            system.assertEquals(0, t1Test9.MarginRecognised__c); //check rev1 margin was removed from target
            
            //Test Revenue__c on undelete
            undelete rev1;
            
            Target__c t1Test10 = [SELECT RevenueRecognised__c, MarginRecognised__c FROM Target__c WHERE Id = :t1.Id];
            
            system.assertEquals(rev1update1.GrossAmount__c, t1Test10.RevenueRecognised__c); //check rev1 amount was added to target
            system.assertEquals(rev1update1.GrossMargin__c, t1Test10.MarginRecognised__c); //check rev1 margin was added to target
            Test.stopTest();
            //Test the WebService
            globalTargetMethods.updateThisTarget(t1.Id);
 
        }
    
    }
    
}