unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Error_Details__c.field-meta.xml
<CustomField>
    <fullName>Error_Details__c</fullName>
    <label>Error Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Error_Summary__c.field-meta.xml
<CustomField>
    <fullName>Error_Summary__c</fullName>
    <label>Error Summary</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/MXPlus_Data__mdt/MXPlus_Data__mdt.object-meta.xml
<CustomObject>
    <label>MX+ Data</label>
    <pluralLabel>MX+ Data</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/MXPlus_Data__mdt/fields/AuthToken__c.field-meta.xml
<CustomField>
    <fullName>AuthToken__c</fullName>
    <label>Auth Token</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/MXPlus_Data__mdt/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/MXPlusTransactionActivity__c.object-meta.xml
<CustomObject>
    <description>Represents an individual MX+ Transaction Activity</description>
    <label>MX+ Transaction Activity</label>
    <nameField>
        <displayFormat>MX+-Act-{0000}</displayFormat>
        <label>MX+ Transaction Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MX+ Transaction Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/DataServicesOwner__c.field-meta.xml
<CustomField>
    <fullName>DataServicesOwner__c</fullName>
    <description>Name of the Data Services person who has taken ownership of the ticket.</description>
    <label>Data Services Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/OEMTotalDataSize__c.field-meta.xml
<CustomField>
    <fullName>OEMTotalDataSize__c</fullName>
    <description>OEM Total Data Size</description>
    <label>OEM Total Data Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/OEMTotalFiles__c.field-meta.xml
<CustomField>
    <fullName>OEMTotalFiles__c</fullName>
    <description>OEM Total Files</description>
    <label>OEM Total Files</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/ServiceDataDirection__c.field-meta.xml
<CustomField>
    <fullName>ServiceDataDirection__c</fullName>
    <description>MX+ Transaction Service Data Direction</description>
    <inlineHelpText>Transaction Service Data Direction</inlineHelpText>
    <label>Service Data Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/ServiceProviderTotalDataSize__c.field-meta.xml
<CustomField>
    <fullName>ServiceProviderTotalDataSize__c</fullName>
    <description>Service Provider Total Data Size</description>
    <label>Service Provider Total Data Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/ServiceProviderTotalFiles__c.field-meta.xml
<CustomField>
    <fullName>ServiceProviderTotalFiles__c</fullName>
    <description>Service Provider Total Files</description>
    <label>Service Provider Total Files</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/SupplierTotalDataSize__c.field-meta.xml
<CustomField>
    <fullName>SupplierTotalDataSize__c</fullName>
    <description>Supplier Total Data Size</description>
    <label>Supplier Total Data Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/SupplierTotalFiles__c.field-meta.xml
<CustomField>
    <fullName>SupplierTotalFiles__c</fullName>
    <description>Supplier Total Files</description>
    <label>Supplier Total Files</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TotalComments__c.field-meta.xml
<CustomField>
    <fullName>TotalComments__c</fullName>
    <description>Total Number of Comments</description>
    <label>Total Comments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionClosedDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionClosedDate__c</fullName>
    <description>Transaction Closed Date</description>
    <label>Transaction Closed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionClosedTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionClosedTime__c</fullName>
    <description>Transaction Closed Time</description>
    <label>Transaction Closed Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionCOO__c.field-meta.xml
<CustomField>
    <fullName>TransactionCOO__c</fullName>
    <description>MX+ Transaction COO</description>
    <inlineHelpText>Transaction COO</inlineHelpText>
    <label>Transaction COO</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <description>Transaction Date</description>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionHours__c.field-meta.xml
<CustomField>
    <fullName>TransactionHours__c</fullName>
    <description>Transaction Hours</description>
    <label>Transaction Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionID__c.field-meta.xml
<CustomField>
    <fullName>TransactionID__c</fullName>
    <description>Transaction ID</description>
    <externalId>true</externalId>
    <label>Transaction ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionOEMPick__c.field-meta.xml
<CustomField>
    <fullName>TransactionOEMPick__c</fullName>
    <label>Transaction OEM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MX_OEM</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionService__c.field-meta.xml
<CustomField>
    <fullName>TransactionService__c</fullName>
    <description>Transaction Service</description>
    <label>Transaction Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionServiceCategory__c.field-meta.xml
<CustomField>
    <fullName>TransactionServiceCategory__c</fullName>
    <description>Transaction Service Category</description>
    <label>Transaction Service Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionStatusPick__c.field-meta.xml
<CustomField>
    <fullName>TransactionStatusPick__c</fullName>
    <description>The Status of this transaction</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Errored</fullName>
            </value>
            <value>
                <fullName>NOT_READY</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionSupplier__c.field-meta.xml
<CustomField>
    <fullName>TransactionSupplier__c</fullName>
    <description>MX+ Transaction Supplier</description>
    <inlineHelpText>Transaction Supplier</inlineHelpText>
    <label>Transaction Supplier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionTime__c</fullName>
    <description>Transaction Time</description>
    <label>Transaction Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/TransactionUserGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionUserGroup__c</fullName>
    <description>MX + Transaction User Group</description>
    <inlineHelpText>Transaction User Group</inlineHelpText>
    <label>Transaction User Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/UserFullName__c.field-meta.xml
<CustomField>
    <fullName>UserFullName__c</fullName>
    <description>User Full Name</description>
    <label>User Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <description>MX User ID</description>
    <label>UserID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MXPlusTransactionActivity__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>MX Username</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/MX_OEM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jaguar Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Nissan</fullName>
    </customValue>
    <customValue>
        <fullName>Majenta</fullName>
    </customValue>
    <customValue>
        <fullName>The Works</fullName>
    </customValue>
    <customValue>
        <fullName>Aston Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Lotus</fullName>
    </customValue>
    <customValue>
        <fullName>Polestar</fullName>
    </customValue>
    <customValue>
        <fullName>Varroc</fullName>
    </customValue>
    <customValue>
        <fullName>Ford Motor Company</fullName>
    </customValue>
    <customValue>
        <fullName>Porsche GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>JLR PTO</fullName>
    </customValue>
    <customValue>
        <fullName>ASG Group</fullName>
    </customValue>
    <customValue>
        <fullName>BMI Group MFG</fullName>
    </customValue>
    <customValue>
        <fullName>EDAG Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Envisage Group</fullName>
    </customValue>
    <customValue>
        <fullName>Lotus Tech Creative Centre (Geely)</fullName>
    </customValue>
    <customValue>
        <fullName>M-Tec Group</fullName>
    </customValue>
    <customValue>
        <fullName>OMR</fullName>
    </customValue>
    <customValue>
        <fullName>Prodrive</fullName>
    </customValue>
    <customValue>
        <fullName>Techniplast</fullName>
    </customValue>
    <customValue>
        <fullName>Unipart Powertrain Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Vingineering Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>WHS Plastics</fullName>
    </customValue>
    <customValue>
        <fullName>Xandor</fullName>
    </customValue>
    <customValue>
        <fullName>Parable Global</fullName>
    </customValue>
    <description>OEMs for MX (MX Data)</description>
    <masterLabel>MX OEM</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GetMXPlusDatainSF.cls
public class GetMXPlusDatainSF {
    @AuraEnabled
    public static Boolean passToLWC( String token, String transactionOrg,  String startDateTime, String endDateTime){
		processMXPlusData(token, transactionOrg, startDateTime, endDateTime);
        return true;
    }
    
    @future(callout=true)
    public static void processMXPlusData(String token, String transactionOrg,  String startDateTime, String endDateTime) {
        Time txTimeValue;
        Time txClosedTimeValue;
		String responsebody = '' ;
        List<MXPlusJSON> txList = new List<MXPlusJSON>();
        
        try{
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://access.mymxdata.com/mxext/api/v1/elastic/transactionplus?datestart='+startDateTime+'&dateend='+endDateTime);
            req.setHeader('Authorization', 'Bearer' + token);
            req.setHeader('Content-type', 'application/json');
            req.setMethod('GET');
            req.setTimeout(20000);
            
            HttpResponse res = new HttpResponse();
            res = h.send(req);
            
            if (res.getStatusCode() == 200) {
                responsebody = res.getBody();
                System.debug(responseBody);
                txList = MXPlusJSON.parse(responseBody);
                System.debug(txList.size()+ 'wrappersize---');
                
                List<MXPlusTransactionActivity__c> mxPlusTxActivities  = new List<MXPlusTransactionActivity__c>();
                List<MXPlusTransactionActivity__c> updatedMxPlusTxActivities  = new List<MXPlusTransactionActivity__c>();
                
                // Map<String,String> mapTransactionIdToSFID	   = new Map<String,String>();
                // Set<String> transactionIdsFromCallout 		   = new Set<String>();
    			
                // String activityId = '';
                List<MXPlusTransactionActivity__c> extantTx = [SELECT TransactionID__c FROM MXPlusTransactionActivity__c];
                List<String> extantTxIds = new List<String>();
                // Updated Record Checks
                for (Integer i = 0; i < extantTx.size(); i++) {
                    extantTxIds.add(extantTx[i].TransactionID__c);
                }
                System.debug('DH DEBUG>>> Extant TX Size: ' +extantTx.size());
                                
                for(integer i=0; i<txList.size(); i++){
                    String[] txTimeString = txList[i].transaction_time.split(':');
                    txTimeValue = Time.newInstance(Integer.valueOf(txTimeString[0]),Integer.valueOf(txTimeString[1]),Integer.valueOf(txTimeString[2]),00);
                    if (String.isEmpty(txList[i].transaction_closedtime)) {
                        txClosedTimeValue = null;
                    }
                    else {
                    String[] txClosedTimeString = txList[i].transaction_closedtime.split(':');
                    txClosedTimeValue = Time.newInstance(Integer.valueOf(txClosedTimeString[0]),Integer.valueOf(txClosedTimeString[1]),Integer.valueOf(txClosedTimeString[2]),00);
                    }
                    Date txClosedDate;
                    if (String.isEmpty(txList[i].transaction_closeddate)) {
                        txClosedDate = null;
                    }
                    else {
                        txClosedDate = Date.valueOf(txList[i].transaction_closeddate);
                    }
                    if (extantTxIds.contains(txList[i].transaction_id)) {
                        System.debug('DH DEBUG>>> Record Exists : ' +txList[i].transaction_id);
                        MXPlusTransactionActivity__c updatedMxPlusTxActivity = new MXPlusTransactionActivity__c(
                        // TransactionDate__c = date.valueof(txList[i].transaction_date),
                        // TransactionTime__c = txTimeValue,
                        TransactionID__c = txList[i].transaction_id,
                        TransactionService__c = txList[i].transaction_service,
                        TransactionServiceCategory__c = txList[i].transaction_servicecategory,
                        TransactionClosedDate__c = txClosedDate,
                        TransactionClosedTime__c = txClosedTimeValue,
                        SupplierTotalDataSize__c = txList[i].transaction_supplier_totaldatasize,
                        SupplierTotalFiles__c = txList[i].transaction_supplier_totalfiles,
                        OEMTotalDataSize__c = txList[i].transaction_oem_totaldatasize,
                        OEMTotalFiles__c = txList[i].transaction_oem_totalfiles,
                        ServiceProviderTotalDataSize__c = txList[i].transaction_serviceprovider_totaldatasize,
                        ServiceProviderTotalFiles__c = txList[i].transaction_serviceprovider_totalfiles,
                        TotalComments__c = txList[i].transaction_totalcomments,
                        TransactionHours__c = txList[i].transaction_hours,
                        ServiceDataDirection__c = txList[i].transaction_servicedatadirection,
                        TransactionSupplier__c = txList[i].transaction_supplier,
                        TransactionOEMPick__c = txList[i].transaction_oem,
                        TransactionCOO__c = txList[i].transaction_coo,
                        TransactionUserGroup__c = txList[i].transaction_usergroup,
                        DataServicesOwner__c = txList[i].transaction_assigneduser
                        // UserFullName__c = txList[i].user_full_name,
                        // UserID__c = txList[i].user_id,
                        // UserName__c = txList[i].user_username
                    );
                    updatedMxPlusTxActivities.add(updatedMxPlusTxActivity);
                    }
                    else {
                        MXPlusTransactionActivity__c mxPlusTxActivity = new MXPlusTransactionActivity__c(
                        TransactionDate__c = date.valueof(txList[i].transaction_date),
                        TransactionTime__c = txTimeValue,
                        TransactionID__c = txList[i].transaction_id,
                        TransactionService__c = txList[i].transaction_service,
                        TransactionServiceCategory__c = txList[i].transaction_servicecategory,
                        TransactionClosedDate__c = txClosedDate,
                        TransactionClosedTime__c = txClosedTimeValue,
                        SupplierTotalDataSize__c = txList[i].transaction_supplier_totaldatasize,
                        SupplierTotalFiles__c = txList[i].transaction_supplier_totalfiles,
                        OEMTotalDataSize__c = txList[i].transaction_oem_totaldatasize,
                        OEMTotalFiles__c = txList[i].transaction_oem_totalfiles,
                        ServiceProviderTotalDataSize__c = txList[i].transaction_serviceprovider_totaldatasize,
                        ServiceProviderTotalFiles__c = txList[i].transaction_serviceprovider_totalfiles,
                        TotalComments__c = txList[i].transaction_totalcomments,
                        TransactionHours__c = txList[i].transaction_hours,
                        TransactionStatusPick__c = txList[i].transaction_status,
                        ServiceDataDirection__c = txList[i].transaction_servicedatadirection,
                        TransactionSupplier__c = txList[i].transaction_supplier,
                        TransactionOEMPick__c = txList[i].transaction_oem,
                        TransactionCOO__c = txList[i].transaction_coo,
                        TransactionUserGroup__c = txList[i].transaction_usergroup,
                        UserFullName__c = txList[i].user_full_name,
                        UserID__c = txList[i].user_id,
                        UserName__c = txList[i].user_username,
                        DataServicesOwner__c = txList[i].transaction_assigneduser
                    );
                    mxPlusTxActivities.add(mxPlusTxActivity);
                    } 
                    //String transactionID = txList[i].transaction_id;
                    // activityId = txList[i].transaction_id+'-'+txList[i].transaction_time+'-'+i;    
                }
                if(updatedMxPlusTxActivities.size()>0){
                    Database.UpsertResult[] updateResults = Database.upsert(updatedMxPlusTxActivities, MXPlusTransactionActivity__c.TransactionID__c, false);
    
                for (Integer i = 0; i < updateResults.size(); i++) {
                    if (updateResults[i].isSuccess()) {
                        System.debug('Successfully updated ID: '+ updateResults[i].getId());
                    } 
                    else {
                        System.debug('Update Error: could not update record ' + 'for array element ' + i + '.');
                        System.debug('   The error reported was: ' + updateResults[i].getErrors()[0].getMessage() + '\n');
                    }
                }
                }
                SObject[] sobjList = new List<SObject>();
                sobjList.addAll(mxPlusTxActivities);
                // sobjList.addAll(mxRecipients);
                Database.SaveResult[] results = Database.insert(sobjList, false);
    
                for (Integer i = 0; i < results.size(); i++) {
                    if (results[i].isSuccess()) {
                        System.debug('Successfully created ID: '+ results[i].getId());
                    } 
                    else {
                        System.debug('Error: could not create sobject ' + 'for array element ' + i + '.');
                        System.debug('   The error reported was: ' + results[i].getErrors()[0].getMessage() + '\n');
                    }
                }
            }
            else{
                // String stackTrace = res.getStackTraceString();
                // System.debug('DH DEBUG>>> STack Trace: ' +res.getStackTraceString());
                Error_Log__c err = new Error_Log__c ( Error_Details__c = 'MX+ import has failed on ' +  transactionOrg + 'for the time window  of ' + startDateTime + ' to ' + endDateTime + ' due to an error whilst connecting to the endpoint'  ,
                                                  Error_Summary__c = res.getStatus(),
                                                  Stack_Trace__c   = String.valueOf(res.getStatusCode()));
            	insert err;
            }
            if(Test.isRunningTest())
            {
            throw new applicationException();
            }
        }catch( Exception e){
        	String stackTrace = e.getStackTraceString();
            System.debug('DH DEBUG>>> STack Trace: ' +e.getStackTraceString());
            Error_Log__c err = new Error_Log__c ( Error_Details__c = 'MX+ import has failed on ' + transactionOrg + ' for the time window of ' + startDateTime + ' to ' + endDateTime + ' due to ' + e.getMessage() ,
                                                  Error_Summary__c = e.getTypeName(),
                                                //   Stack_Trace__c   = e.getStackTraceString());
                                                  Stack_Trace__c   =  stackTrace.left(255));
            insert err;
        }        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<MXPlus_Data__mdt> getMetadataRecords(){
        return [ SELECT developerName, masterLabel , AuthToken__c, ServiceProvider__c FROM MXPlus_Data__mdt ];
    }

    public class applicationException extends Exception {}
}