unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/BillingAccount__c.field-meta.xml
<CustomField>
    <fullName>BillingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing)</relationshipLabel>
    <relationshipName>AccountBillingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/BillingAddress2__c.field-meta.xml
<CustomField>
    <fullName>BillingAddress2__c</fullName>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>ENERJYHUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/CustomerOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerOrderNumber__c</fullName>
    <externalId>true</externalId>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/IsClone__c.field-meta.xml
<CustomField>
    <fullName>IsClone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cloned</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/IsFactored__c.field-meta.xml
<CustomField>
    <fullName>IsFactored__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Factored</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Shipping)</relationshipLabel>
    <relationshipName>AccountShippingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/ShippingAddress2__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress2__c</fullName>
    <label>Shipping Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>InvoiceLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CASE(Division__c,
"PLM", "PLM",
"Solid Edge", "PLM",
"COMOS", "PLM",
"MPLM Software Development", "PLM",
"enerjyhub","ENERJYHUB",
"SOLUTIONS"
)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Subscription__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/InvoiceCloneWithItemsController.cls
public class InvoiceCloneWithItemsController {
 
    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
     // add the instance for the variables being passed by id on the url
    private Invoice__c inv {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}
 
    // initialize the controller
    public InvoiceCloneWithItemsController(ApexPages.StandardController controller) {
 
        //initialize the stanrdard controller
        this.controller = controller;
        // load the current record
        inv = (Invoice__c)controller.getRecord();
 
    }
 
    // method called from the VF's action attribute to clone the inv
    public PageReference cloneWithItems() {
 
         // setup the save point for rollback
         Savepoint sp = Database.setSavepoint();
         Invoice__c newInv;
 
         try {
 
             //copy the Invoice - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
             inv = [SELECT Id, Name, BillingAddress2__c, BillingAccount__c, Company__c, CustomerOrderNumber__c, IsFactored__c, IsHeaded__c, Notes__c, Opportunity__c, ShippingAddress2__c, ShippingAccount__c  FROM Invoice__c WHERE Id = :inv.id];
             inv.Date__c = System.Date.today();
             inv.IsClone__c = TRUE;
             newInv = inv.clone(false);
             insert newInv;
 
             // set the id of the new inv created for testing
               newRecordId = newInv.id;
 
             // copy over the line items - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
             List<InvoiceLineItem__c> items = new List<InvoiceLineItem__c>();
             for (InvoiceLineItem__c invLi : [SELECT Id, Name, Description__c, Product__c, ProductType_ro__c, Quantity__c, SortOrder__c, UnitPrice__c, TaxRate__c FROM InvoiceLineItem__c i WHERE Invoice__c = :inv.id]) {
                  InvoiceLineItem__c newInvLi = invLi.clone(false);
                  newInvLi.Invoice__c = newInv.id;
                  items.add(newInvLi);
             }
             insert items;
 
         } catch (Exception e){
             // roll everything back in case of error
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
         }
 
        return new PageReference('/'+newInv.id+'/e?retURL=%2F'+newInv.id);
    }
    
    @isTest
    private static void testInvCloneController() {
 
       // setup a reference to the page the controller is expecting with the parameters
        PageReference pref = Page.InvoiceClone;
        Test.setCurrentPage(pref);
 
        // setup a ship to account
        Account shipTo = new Account();
        shipTo.Name = 'PSAV 6FOO';
        shipTo.Type = 'Customer';
        insert shipTo;
        
        //Insert Test Opportunity
        Opportunity Opp = new Opportunity( Name = 'TestOpp',
                                           CloseDate = System.Date.today(),
                                           StageName = 'Order Received'
                                         );
        insert Opp;
 
        // create new inv record
        Invoice__c inv = new Invoice__c();
        inv.Opportunity__c = Opp.id;
        inv.Date__c = system.today();//Date.newInstance(2020,01,01);
        inv.ShippingAccount__c = shipTo.id;
        insert inv;
 
        // create a line item for the inv
        InvoiceLineItem__c invLi1 = new InvoiceLineItem__c();
        invLi1.Description__c = 'My item';
        invLi1.Invoice__c = inv.id;
        invLi1.Quantity__c = 1;
        invLi1.UnitPrice__c = 10;
        insert invLi1;
 
        // Construct the standard controller
        ApexPages.StandardController con = new ApexPages.StandardController(inv);
 
        // create the controller
        InvoiceCloneWithItemsController ext = new InvoiceCloneWithItemsController(con);
 
        // Switch to test context
        Test.startTest();
 
        // call the cloneWithItems method
        PageReference ref = ext.cloneWithItems();
        // create the matching page reference
        PageReference redir = new PageReference('/'+ext.newRecordId+'/e?retURL=%2F'+ext.newRecordId);
 
        // make sure the user is sent to the correct url
        System.assertEquals(ref.getUrl(),redir.getUrl());
 
        // check that the new inv was created successfully
        Invoice__c newInv = [SELECT id from Invoice__c WHERE id = :ext.newRecordId];
        System.assertNotEquals(newInv, null);
        // check that the line item was created
        List<InvoiceLineItem__c> newItems = [SELECT i.Id From InvoiceLineItem__c i WHERE Invoice__c = :newInv.id];
        System.assertEquals(newItems.size(),1);
 
        // Switch back to runtime context
        Test.stopTest();
 
    }
  
}