unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/IsInvoice__c.field-meta.xml
<CustomField>
    <fullName>IsInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>InvoiceLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>InvoiceJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipName>InvoiceLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/InvoiceTriggerTests.cls
@isTest(seeAllData=true)
public class InvoiceTriggerTests
{
	@isTest(seeAlldata=true)
	public static void testInvoiceTriggers()
	{
		List<InvoiceLineItem__c> invoiceLineItemCache = new List<InvoiceLineItem__c>();
		Product2 product = new Product2(
			Name = 'Apex Test Product',
			Description = 'Test Product Description',
			Family = 'Test',
			ProductCode = 'TEST1234');
		insert product;
		System.assertNotEquals(product.Id, null);
		
		List<User> users = new List<User>([
			SELECT
				Id
			FROM
				User
			WHERE
				Profile.Name = 'System Administrator'
			AND
				IsActive = true
			LIMIT 1]);
		System.assertEquals(users.size(), 1, 'No users, test unable to continue.');
		
		User user = users.get(0);
		System.runAs(user)
		{
			Account account = new Account(
				Name = 'Apex Test Account');
			insert account;
			System.assertNotEquals(account.Id, null);
			
			Opportunity opportunity = new Opportunity(
				Name = 'Apex Test Opportunity',
				AccountId = account.Id,
				Type = 'New Customer New Business',
				CloseDate = Date.today(),
				StageName = 'Order Received');
			insert opportunity;
			System.assertNotEquals(opportunity.Id, null);
			
			Invoice__c invoice = new Invoice__c(
				Opportunity__c = opportunity.Id,
				Date__c = Date.today());
			insert invoice;
			System.assertNotEquals(invoice.Id, null);
			
			for (Integer i = 0; i < 2; i++)
			{
				InvoiceLineItem__c invoiceLineItem = new InvoiceLineItem__c(
					Invoice__c = invoice.Id,
					Product__c = product.Id,
					Name = product.Name + ' #' + i );
				invoiceLineItemCache.add(invoiceLineItem);
			}
			insert invoiceLineItemCache;
			
			invoice.CurrencyIsoCode = 'EUR';
			update invoice;
			
			List<InvoiceLineItem__c> testInvoiceLineItems = new List<InvoiceLineItem__c>([
				SELECT
					Id,
					CurrencyIsoCode
				FROM
					InvoiceLineItem__c
				WHERE
					Invoice__c = :invoice.Id]);
			System.assertEquals(testInvoiceLineItems.size(), 2);
			
			for (InvoiceLineItem__c testInvoiceLineItem : testInvoiceLineItems)
			{
				System.assertEquals(testInvoiceLineItem.CurrencyIsoCode, invoice.CurrencyIsoCode);
			}
			
			Revenue__c revenue = new Revenue__c(
				Name = 'Apex Test Revenue',
				Invoice__c = invoice.Id,
				InvoiceLineItem__c = invoiceLineItemCache.get(0).Id);
			insert revenue;
			System.assertNotEquals(revenue.Id, null);
			
			invoice.IsInvoice__c = true;
			update invoice;
            
            InvoiceLineItem__c invoiceLineItem = [SELECT Id FROM InvoiceLineItem__c WHERE Invoice__c = :invoice.Id LIMIT 1];
            
            try{
                delete invoiceLineItem;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot delete a Line Item from an Invoice that has been Invoiced.') ? true : false;
            }
            
            invoice.IsInvoice__c = FALSE;
            update invoice;
            
            delete invoiceLineItem;
            
            invoice.IsInvoice__c = TRUE;
            update invoice;
            
            try{
                undelete invoiceLineItem;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot undelete a Line Item from an Invoice that has been Invoiced.') ? true : false;
            }
            
        }   
 
    }
}