unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <formula>IF(LEFT(Name,3) == "INV",
  Opportunity__r.Quote_Number_Revised__c+"-"+Name,
  Opportunity__r.Quote_Number_Revised__c+"-"+CompanyAbbr__c+Name
)</formula>
    <label>Invoice Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/IsInvoice__c.field-meta.xml
<CustomField>
    <fullName>IsInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Total Net Amount</label>
    <summarizedField>InvoiceLineItem__c.NetAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>InvoiceNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SI"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(Invoice__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>CASE(ProductType_ro__c,
	"Software", SoftwareMargin__c,
	"Hardware", HardwareMargin__c,
	"Services", ServicesMargin__c,
	"Maintenance", MaintenanceMargin__c,
	OtherMargin__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <formula>TEXT(Product__r.Family)</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin (Legacy)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>InvoiceJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipName>InvoiceLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>CASE(Type__c,
"SI",  GrossAmount__c,
"SC", (0 - GrossAmount__c),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/InvoiceTriggerHandler.cls
public with sharing class InvoiceTriggerHandler {

    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
        
    public InvoiceTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
    globalRevenueRecognisedMethods.RevenueRecognisedMethods rev = new globalRevenueRecognisedMethods.RevenueRecognisedMethods();
              
    //public void OnBeforeInsert(Invoice__c[] newInvoices){        
    //}
    
    //public void OnAfterInsert(Invoice__c[] newInvoices){
    //}
    
    //@future public static void OnAfterInsertAsync(Set<ID> newInvoiceIDs){
    //}
    
    //public void OnBeforeUpdate(Invoice__c[] oldInvoices,Invoice__c[] updatedInvoices, Map<ID, Invoice__c> InvoiceMap){
    //}
    
    public void OnAfterUpdate(Invoice__c[] oldInvoices, Invoice__c[] updatedInvoices, Map<ID,  Invoice__c> oldInvoiceMap, Map<ID,  Invoice__c> newInvoiceMap){

        List<InvoiceLineItem__c> invoiceLineItemCache = new List<InvoiceLineItem__c>();
        List<Revenue__c> revenue2DeleteList = new List<Revenue__c>();
        List<Invoice__c> invoiceCache = new List<Invoice__c>();  


        for (Invoice__c invoice : [
                    SELECT
                        Opportunity__r.OwnerId,
                        Opportunity__r.Id,
                        Id,
                        Ref__c,
                        IsInvoice__c,
                        CurrencyIsoCode,
                        InvoiceNumber__c,
                        Date__c,
                        Type__c, (
                        SELECT
                            Id
                        FROM
                            InvoiceJournalEntries__r), (
                        SELECT
                            Id,
                            CurrencyIsoCode,
                            NetAmount__c,
                            ProductType__c,
                            Margin__c,
                            ProductFamily__c,
                            BusinessType__c
                        FROM
                            InvoiceLineItems__r)
                    FROM
                        Invoice__c
                    WHERE
                        Id IN :newInvoiceMap.keySet()])
        {

            Invoice__c oldInvoice = oldInvoiceMap.get(invoice.Id);

            //Check if Invoice Currency has changed and update the line items to match
            if (invoice.CurrencyIsoCode != oldInvoice.CurrencyIsoCode){
                for (InvoiceLineItem__c invoiceLineItem : invoice.InvoiceLineItems__r){
                    invoiceLineItem.CurrencyIsoCode = invoice.CurrencyIsoCode;
                }

                invoiceLineItemCache.addAll(invoice.InvoiceLineItems__r);
            }

            //Check if Invoice status has been changed
            if (invoice.IsInvoice__c != oldInvoice.IsInvoice__c){

                //Remove all current Revenue Entries
                revenue2DeleteList.addAll(invoice.InvoiceJournalEntries__r);
                //Generate new Revenue Entries for Completed Invoice
                if (invoice.IsInvoice__c){
                    invoiceCache.add(invoice);
                }

            }

        }

        if (!revenue2DeleteList.isEmpty()){
            delete revenue2DeleteList;
        }
        
        if (!invoiceLineItemCache.isEmpty()){
            update invoiceLineItemCache;
        } 
        
        if (!invoiceCache.isEmpty()){
            rev.generateRevenueRecognised(invoiceCache);
        }

    }
    
    //@future public static void OnAfterUpdateAsync(Set<ID> updatedTaskIDs){
    //}
    
    //public void OnBeforeDelete(Invoice__c[] InvoicesToDelete, Map<ID, Invoice__c> InvoiceMap){
    //}
    
    //public void OnAfterDelete(Invoice__c[] deletedInvoices, Map<ID, Invoice__c> InvoiceMap){
    //}
    
    //@future public static void OnAfterDeleteAsync(Set<ID> deletedTaskIDs){
    //}
    
    //public void OnUndelete(Invoice__c[] restoredInvoices){
    //}
    
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
    
    public boolean IsVisualforcePageContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsWebServiceContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsExecuteAnonymousContext{
        get{ return !IsTriggerContext;}
    }
}