unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Total Net Amount</label>
    <summarizedField>CreditNoteLineItem__c.NetAmount__c</summarizedField>
    <summaryForeignKey>CreditNoteLineItem__c.CreditNote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>CreditNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SC"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(CreditNote__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/BusinessType_ro__c.field-meta.xml
<CustomField>
    <fullName>BusinessType_ro__c</fullName>
    <label>Business Type (Read Only)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <formula>TEXT(Product__r.Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/ProductType_ro__c.field-meta.xml
<CustomField>
    <fullName>ProductType_ro__c</fullName>
    <label>Product Type (Read Only)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Total Net Amount</label>
    <summarizedField>InvoiceLineItem__c.NetAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>InvoiceNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SI"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(Invoice__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>CASE(ProductType_ro__c,
	"Software", SoftwareMargin__c,
	"Hardware", HardwareMargin__c,
	"Services", ServicesMargin__c,
	"Maintenance", MaintenanceMargin__c,
	OtherMargin__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <formula>TEXT(Product__r.Family)</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/ProductFamily_ro__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily_ro__c</fullName>
    <label>Product Family (Read Only)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin (Legacy)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Business_Type_ro__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_ro__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(PricebookEntry.Product2.NewBusiness__c,
    "New",
    CASE( Opportunity.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type (Data)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>(TotalPrice -  Total_Buy__c) + TotalAutodeskTBP__c + TotalAutodeskVIR__c + TotalDatechEarnback__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Product_Family_ro__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_ro__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Product_Type_ro__c.field-meta.xml
<CustomField>
    <fullName>Product_Type_ro__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <formula>TEXT( PricebookEntry.Product2.Type__c )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Total_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Sale_Price__c</fullName>
    <formula>UnitPrice  *  Quantity</formula>
    <label>Total Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipName>CreditNoteJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note Line Item</label>
    <referenceTo>CreditNoteLineItem__c</referenceTo>
    <relationshipName>CreditNoteLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/GrossAmount__c.field-meta.xml
<CustomField>
    <fullName>GrossAmount__c</fullName>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>InvoiceJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipName>InvoiceLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>CASE(Type__c,
"SI",  GrossAmount__c,
"SC", (0 - GrossAmount__c),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/globalRevenueRecognisedMethods.cls
global class globalRevenueRecognisedMethods {
    
    public without sharing class RevenueRecognisedMethods {
        
        public void generateRevenueRecognised(List<SObject> data) {
                        
            if(data != null && !data.isEmpty()) {
                
                List<SObject> records = new List<SObject>();
                List<Revenue__c> newRevs = new List<Revenue__c>();
                
                //Get Object Type of data List
                String objectType = data.getSObjectType().getDescribe().getName();
                                
                if(objectType == 'Invoice__c' || objectType == 'CreditNote__c'){
                    records.addAll(data);
                }
                else if(objectType == 'Opportunity'){
                    for(SObject opp : data){
                        records.addAll(opp.getSObjects('OpportunityInvoices__r'));
                        records.addAll(opp.getSObjects('OpportunityCreditNotes__r'));
                    }
                }
                                                  
                for(SObject record : records){
                    String recordType = record.getSObjectType().getDescribe().getName();
                    String recordId = String.valueOf(record.get('Id'));
                    String oppId = String.valueOf(record.getSObject('Opportunity__r').get('Id'));
                    
                    Map<Map<String,String>,Map<String,Decimal>> oppRevMap = new Map<Map<String,String>,Map<String,Decimal>>();                        
                    
                    List<AggregateResult> oppTotals = [SELECT Product_Family_ro__c, Business_Type_ro__c, Product_Type_ro__c, SUM(Total_Sale_Price__c), SUM(Margin__c) FROM OpportunityLineItem  WHERE Opportunity.Id =: oppId GROUP BY ROLLUP(Product_Family_ro__c, Business_Type_ro__c, Product_Type_ro__c ) HAVING Product_Type_ro__c != ''];
                    List<AggregateResult> recordTotals = new List<AggregateResult>();
                    if(recordType == 'Invoice__c'){                    
                    	recordTotals = [SELECT ProductFamily_ro__c, BusinessType_ro__c, ProductType_ro__c, SUM(NetAmount__c) from InvoiceLineItem__c WHERE Invoice__r.Id =: recordId GROUP BY ROLLUP(ProductFamily_ro__c, BusinessType_ro__c, ProductType_ro__c) HAVING ProductType_ro__c != ''];
                    }
                    else if(recordType == 'CreditNote__c'){
                        recordTotals = [SELECT ProductFamily_ro__c, BusinessType_ro__c, ProductType_ro__c, SUM(NetAmount__c) from CreditNoteLineItem__c WHERE CreditNote__r.Id =: recordId GROUP BY ROLLUP(ProductFamily_ro__c, BusinessType_ro__c, ProductType_ro__c) HAVING ProductType_ro__c != ''];
                    }
                    
                    for(AggregateResult oppTotal : oppTotals){
                        
                        String productFamily = (String) oppTotal.get('Product_Family_ro__c');
                        String businessType = (String) oppTotal.get('Business_Type_ro__c');
                        String productType = (String) oppTotal.get('Product_Type_ro__c');
                        Decimal revenueTotal = (Decimal) oppTotal.get('expr0');
                        Decimal marginTotal = (Decimal) oppTotal.get('expr1');
                        
                        //Skip entries without third level groupings
                        //if(productType == null){
                        //    continue;
                        //}
                        
                        //Build the Key Map
                        Map<String,String> keyMap = new Map<String,String>{
                            'productFamily' => productFamily,
                            'businessType' => businessType,
                            'productType' => productType
                        };
                                    
                        //Build the Value Map    
                        Map<String,Decimal> valueMap = new Map<String,Decimal>{
                            'revenue' => revenueTotal,
                            'margin' => marginTotal
                        };
                                        
                        //Add Key and Value Maps to the Opportunity Revenue Map
                        oppRevMap.put(keyMap, valueMap);
                        
                    }
                    
                    for(AggregateResult recordTotal : recordTotals){
                        
                        String productFamily = (String) recordTotal.get('ProductFamily_ro__c');
                        String businessType = (String) recordTotal.get('BusinessType_ro__c');
                        String productType = (String) recordTotal.get('ProductType_ro__c');
                        Decimal revenueTotal = (Decimal) recordTotal.get('expr0');
                        Decimal revenuePercent = 0;
                        Decimal marginTotal = 0;
                        Revenue__c newRev = new Revenue__c();
                        
                        //Skip entries without third level groupings
                        //if(productType == null){
                        //    continue;
                        //}
                        
                        Map<String,String> keyMap = new Map<String,String>{
                            'productFamily' => productFamily,
                            'businessType' => businessType,
                            'productType' => productType
                        };
                                    
                        if(oppRevMap.get(keyMap) != null){
                            //Calculate the percentage difference between this invoice and the total deal amount
                            if(oppRevMap.get(keyMap).get('revenue') != null && oppRevMap.get(keyMap).get('revenue') <> 0){
                                revenuePercent = revenueTotal / oppRevMap.get(keyMap).get('revenue');
                            }
                            //Calculate the margin amount based on the above percentage
                            if(oppRevMap.get(keyMap).get('margin') != null){
                                marginTotal = oppRevMap.get(keyMap).get('margin') * revenuePercent;
                            }
                        }
                        
                        newRev.Name = String.valueOf(record.get('Ref__c'));
                        newRev.OwnerId = String.valueOf(record.getSObject('Opportunity__r').get('OwnerId'));
                        newRev.Opportunity__c = oppId;
                        if(recordType == 'Invoice__c'){
                            newRev.Invoice__c = recordId;
                        }
                        else if(recordType == 'CreditNote__c'){
                            newRev.CreditNote__c = recordId;
                        }
                        newRev.Date__c = Date.valueOf(record.get('Date__c'));
                        newRev.Type__c = String.valueOf(record.get('Type__c'));
                        newRev.ProductFamily__c = productFamily;
                        newRev.BusinessType__c = businessType;
                        newRev.ProductType__c = productType;
                        newRev.GrossAmount__c = revenueTotal;
                        newRev.GrossMargin__c = marginTotal;
                        
                        newRevs.add(newRev);
                    }
                    
                }
                
                if(!newRevs.isEmpty()){
                    insert newRevs;
                }
            }
            
        }
        
    }
    
    WebService static String[] generateInvoiceRevRec(String invId){
        List<String> message = new List<String>();
        List<Revenue__c> deleteRevs = new List<Revenue__c>();
        
        globalRevenueRecognisedMethods.RevenueRecognisedMethods rev = new globalRevenueRecognisedMethods.RevenueRecognisedMethods();
        
        Invoice__c[] Invoices = [ SELECT Id, Ref__c, IsInvoice__c, Date__c, Type__c, Opportunity__r.Id, Opportunity__r.OwnerId, (SELECT Id FROM InvoiceJournalEntries__r) FROM Invoice__c WHERE Id =: invId AND IsInvoice__c = TRUE];
        deleteRevs.addAll(Invoices[0].InvoiceJournalEntries__r);
        
        if (!deleteRevs.isEmpty()){
			delete deleteRevs;
		}
        
        if (!Invoices.isEmpty()){
            rev.generateRevenueRecognised(Invoices);
        }
        
        return message;   
	}
    
    WebService static String[] generateOppRevRec(String oppId){
        List<String> message = new List<String>();
        List<Invoice__c> Invoices = new List<Invoice__c>();
        List<CreditNote__c> Credits = new List<CreditNote__c>();
        List<Revenue__c> deleteRevs = new List<Revenue__c>();
        
        globalRevenueRecognisedMethods.RevenueRecognisedMethods rev = new globalRevenueRecognisedMethods.RevenueRecognisedMethods();
        
        Opportunity opp = [SELECT Id,
                          		  (SELECT Id, 
                                   		  Ref__c,
                                   		  IsInvoice__c,
                                    	  Date__c,
                                    	  Type__c,
                                   		  Opportunity__r.Id,
                                   		  Opportunity__r.OwnerId 
                                   FROM OpportunityInvoices__r 
                                   WHERE IsInvoice__c = TRUE),
                           		  (SELECT Id,
                                   		  Ref__c,
                                   		  IsCredited__c,
                                   		  Date__c,
                                   		  Type__c,
                                   		  Opportunity__r.Id,
                                   		  Opportunity__r.OwnerId 
                                   FROM OpportunityCreditNotes__r 
                                   WHERE IsCredited__c = TRUE),
                           		  (SELECT Id 
                                   FROM RevenueRecognised__r)
                           FROM Opportunity 
                           WHERE Id =: oppId 
                           LIMIT 1];
        
        Invoices.addAll(opp.OpportunityInvoices__r);
        Credits.addAll(opp.OpportunityCreditNotes__r);        
        deleteRevs.addAll(opp.RevenueRecognised__r);
        
        if (!deleteRevs.isEmpty()){
			delete deleteRevs;
		}
        
        if (!Invoices.isEmpty()){
            rev.generateRevenueRecognised(invoices);
        }
        
        if (!Credits.isEmpty()){
            rev.generateRevenueRecognised(credits);
        }
        
        return message;   
	}

}