unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/CreditNumber__c.field-meta.xml
<CustomField>
    <fullName>CreditNumber__c</fullName>
    <formula>Opportunity__r.Quote_Number_Revised__c+"-"+CompanyAbbr__c+"-"+Name</formula>
    <label>Credit Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/IsCredited__c.field-meta.xml
<CustomField>
    <fullName>IsCredited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Total Net Amount</label>
    <summarizedField>CreditNoteLineItem__c.NetAmount__c</summarizedField>
    <summaryForeignKey>CreditNoteLineItem__c.CreditNote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>CreditNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SC"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(CreditNote__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <formula>TEXT(Product__r.Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin (Legacy)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipName>CreditNoteJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note Line Item</label>
    <referenceTo>CreditNoteLineItem__c</referenceTo>
    <relationshipName>CreditNoteLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>CASE(Type__c,
"SI",  GrossAmount__c,
"SC", (0 - GrossAmount__c),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CreditNoteTriggerHandler.cls
public with sharing class CreditNoteTriggerHandler {

    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
        
    public CreditNoteTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
    globalRevenueRecognisedMethods.RevenueRecognisedMethods rev = new globalRevenueRecognisedMethods.RevenueRecognisedMethods();
              
    //public void OnBeforeInsert(CreditNote__c[] newCreditNotes){        
    //}
    
    //public void OnAfterInsert(CreditNote__c[] newCreditNotes){
    //}
    
    //@future public static void OnAfterInsertAsync(Set<ID> newCreditNoteIDs){
    //}
    
    //public void OnBeforeUpdate(CreditNote__c[] oldCreditNotes,CreditNote__c[] updatedCreditNotes, Map<ID, CreditNote__c> CreditNoteMap){
    //}
    
    public void OnAfterUpdate(CreditNote__c[] oldCreditNotes, CreditNote__c[] updatedCreditNotes, Map<ID,  CreditNote__c> oldCreditNoteMap, Map<ID,  CreditNote__c> newCreditNoteMap){

        List<CreditNoteLineItem__c> creditNoteLineItemCache = new List<CreditNoteLineItem__c>();
        List<Revenue__c> revenue2DeleteList = new List<Revenue__c>();
        List<CreditNote__c> creditNoteCache = new List<CreditNote__c>();  


        for (CreditNote__c creditNote : [
                    SELECT
                        Opportunity__r.OwnerId,
                        Opportunity__r.Id,
                        Id,
                        Ref__c,
                        IsCredited__c,
                        CurrencyIsoCode,
                        CreditNumber__c,
                        Date__c,
                        Type__c, (
                        SELECT
                            Id
                        FROM
                            CreditNoteJournalEntries__r), (
                        SELECT
                            Id,
                            CurrencyIsoCode,
                            NetAmount__c,
                            ProductType__c,
                            Margin__c,
                            ProductFamily__c,
                            BusinessType__c
                        FROM
                            CreditNoteLineItems__r)
                    FROM
                        CreditNote__c
                    WHERE
                        Id IN :newCreditNoteMap.keySet()])
        {

            CreditNote__c oldCreditNote = oldCreditNoteMap.get(creditNote.Id);

            //Check if CreditNote Currency has changed and update the line items to match
            if (creditNote.CurrencyIsoCode != oldCreditNote.CurrencyIsoCode){
                for (CreditNoteLineItem__c creditNoteLineItem : creditNote.CreditNoteLineItems__r){
                    creditNoteLineItem.CurrencyIsoCode = creditNote.CurrencyIsoCode;
                }

                creditNoteLineItemCache.addAll(creditNote.CreditNoteLineItems__r);
            }

            //Check if CreditNote status has been changed
            if (creditNote.IsCredited__c != oldCreditNote.IsCredited__c){

                //Remove all current Revenue Entries
                revenue2DeleteList.addAll(creditNote.CreditNoteJournalEntries__r);
                //Generate new Revenue Entries for Completed CreditNote
                if (creditNote.IsCredited__c){
                    creditNoteCache.add(creditNote);
                }

            }

        }

        if (!revenue2DeleteList.isEmpty()){
            delete revenue2DeleteList;
        }
        
        if (!creditNoteLineItemCache.isEmpty()){
            update creditNoteLineItemCache;
        } 
        
        if (!creditNoteCache.isEmpty()){
            rev.generateRevenueRecognised(creditNoteCache);
        }

    }
    
    //@future public static void OnAfterUpdateAsync(Set<ID> updatedTaskIDs){
    //}
    
    //public void OnBeforeDelete(CreditNote__c[] CreditNotesToDelete, Map<ID, CreditNote__c> CreditNoteMap){
    //}
    
    //public void OnAfterDelete(CreditNote__c[] deletedCreditNotes, Map<ID, CreditNote__c> CreditNoteMap){
    //}
    
    //@future public static void OnAfterDeleteAsync(Set<ID> deletedTaskIDs){
    //}
    
    //public void OnUndelete(CreditNote__c[] restoredCreditNotes){
    //}
    
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
    
    public boolean IsVisualforcePageContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsWebServiceContext{
        get{ return !IsTriggerContext;}
    }
    
    public boolean IsExecuteAnonymousContext{
        get{ return !IsTriggerContext;}
    }
}