unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/IsCredited__c.field-meta.xml
<CustomField>
    <fullName>IsCredited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipName>CreditNoteJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note Line Item</label>
    <referenceTo>CreditNoteLineItem__c</referenceTo>
    <relationshipName>CreditNoteLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CreditNoteTriggerTests.cls
@isTest
public class CreditNoteTriggerTests
{
    @isTest(seeAllData=true)
    public static void testCreditNoteTriggers()
    {
        List<CreditNoteLineItem__c> creditNoteLineItemCache = new List<CreditNoteLineItem__c>();
        Product2 product = new Product2(
            Name = 'Test Product',
            Description = 'Test Product Description',
            Family = 'Test',
            ProductCode = 'TEST1234');
        insert product;
        System.assertNotEquals(product.Id, null);
        
        List<User> users = new List<User>([
            SELECT
                Id
            FROM
                User
            WHERE
                Profile.Name ='System Administrator'
            AND
                IsActive = true
            LIMIT 1]);
        System.assertEquals(users.size(), 1, 'No valid users, test cannot continue.');
        
        User user = users.get(0);
        
        System.runAs(user)
        {
            Account account = new Account(
                Name = 'Apex Test Account');
            insert account;
            System.assertNotEquals(account.Id, null);
            
            Opportunity opportunity = new Opportunity(
                Name = 'Apex Test Opportunity',
                AccountId = account.Id,
                Type = 'New Customer New Business',
                CloseDate = Date.today(),
                StageName = 'Order Received');
            insert opportunity;
            System.assertNotEquals(opportunity.Id, null);
            
            CreditNote__c creditNote = new CreditNote__c(
                Opportunity__c = opportunity.Id,
                Date__c = Date.today());
            insert creditNote;
            System.assertNotEquals(creditNote.Id, null);
            
            for (Integer i = 0; i < 2; i++)
            {
                CreditNoteLineItem__c creditNoteLineItem = new CreditNoteLineItem__c(
                    CreditNote__c = creditNote.Id,
                    Product__c = product.Id,
                    Name = product.Name + ' #' + (1 + 1));
                creditNoteLineItemCache.add(creditNoteLineItem);
            }
            insert creditNoteLineItemCache;
            

            creditNote.CurrencyIsoCode = 'EUR';
            update creditNote;
            
            List<CreditNoteLineItem__c> testCreditNoteLineItems = new List<CreditNoteLineItem__c>([
                SELECT
                    Id,
                    CurrencyIsoCode
                FROM
                    CreditNoteLineItem__c
                WHERE
                    CreditNote__c =: creditNote.Id]);
            System.assertEquals(testCreditNoteLineItems.size(), 2);
  
            for( CreditNoteLineItem__c testCreditNoteLineItem : testCreditNoteLineItems)
            {
                System.AssertEquals( testCreditNoteLineItem.CurrencyIsoCode, creditNote.CurrencyIsoCode);
            }
            
            Revenue__c revenue = new Revenue__c(
                Name = 'Apex Test Revenue',
                CreditNote__c = creditNote.Id,
                CreditNoteLineItem__c = creditNoteLineItemCache.get(0).Id);
            insert revenue;
            System.assertNotEquals(revenue.Id, null);
            
            creditNote.IsCredited__c = TRUE;
            update creditNote;
            
            CreditNoteLineItem__c creditNoteLineItem = [SELECT Id FROM CreditNoteLineItem__c WHERE CreditNote__c = :creditNote.Id LIMIT 1];
            
            try{
                delete creditNoteLineItem;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot delete a Line Item from an Credit Note that has been Credited.') ? true : false;
            }
            
            creditNote.IsCredited__c = FALSE;
            update creditNote;
            
            delete creditNoteLineItem;
            
            creditNote.IsCredited__c = TRUE;
            update creditNote;
            
            try{
                undelete creditNoteLineItem;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot undelete a Line Item from an Credit Note that has been Credited.') ? true : false;
            }
            
            try{
            delete account;
            }
            catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('You cannot delete this record!') ? true : false;
            }
        }   
 
    }
    
}