unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>ENERJYHUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CASE(Division__c,
"PLM", "PLM",
"Solid Edge", "PLM",
"COMOS", "PLM",
"MPLM Software Development", "PLM",
"enerjyhub","ENERJYHUB",
"SOLUTIONS"
)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>OpportunityPurchaseOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/globalEmailPDF_TEST.cls
@isTest()
public class globalEmailPDF_TEST {
    public static testmethod void testEmailPdfMethods(){
        
        User user = [SELECT Id FROM User WHERE Profile.Name ='System Administrator' AND IsActive = TRUE LIMIT 1];
        
        system.runAs(user){
            //Create a new Opportunity
            Opportunity opp1 = new Opportunity();
            opp1.Name = 'Test Opportunity #1';
            opp1.StageName = 'Order Processed';
            opp1.Probability = 100;
            opp1.CloseDate = System.Date.Today();
            opp1.Amount = 1500;
            opp1.Customer_Order_Number__c = '1234';
            insert opp1;
            
            //Create a new Invoice
            Invoice__c inv1 = new Invoice__c();
            inv1.Opportunity__c = opp1.Id;
            inv1.Company__c = 'SOLUTIONS';
            inv1.Date__c = System.Date.Today();
            insert inv1;
            
            globalEmailPDF.emailPDF(inv1.Id,'/apex/InvoiceSingle');
            
            
            //Create a new Credit Note
            CreditNote__c crd1 = new CreditNote__c();
            crd1.Opportunity__c = opp1.Id;
            crd1.Company__c = 'SOLUTIONS';
            crd1.Date__c = System.Date.Today();
            insert crd1;
            
            globalEmailPDF.emailPDF(crd1.Id,'/apex/CreditNoteSingle');
            
            
            //Create a new Purchase Order
            PurchaseOrder__c po1 = new PurchaseOrder__c();
            po1.Opportunity__c = opp1.Id;
            po1.Date__c = System.Date.Today();
            insert po1;
            
            globalEmailPDF.emailPDF(po1.Id,'/apex/PurchaseOrderTemplate');
            
        }
    }
}