unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/IsCredited__c.field-meta.xml
<CustomField>
    <fullName>IsCredited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credited</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>CreditNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SC"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>ENERJYHUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/IsInvoice__c.field-meta.xml
<CustomField>
    <fullName>IsInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>InvoiceNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>"SI"</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType2__c.field-meta.xml
<CustomField>
    <fullName>BusinessType2__c</fullName>
    <label>Business Type (Override)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>InvoiceLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CASE(Division__c,
"PLM", "PLM",
"Solid Edge", "PLM",
"COMOS", "PLM",
"MPLM Software Development", "PLM",
"enerjyhub","ENERJYHUB",
"SOLUTIONS"
)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Subscription__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/BusinessType2__c.field-meta.xml
<CustomField>
    <fullName>BusinessType2__c</fullName>
    <inlineHelpText>This is used to define the business type per product on mixed business deals.</inlineHelpText>
    <label>Business Type (Override)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Expenses</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Overhead</fullName>
            </value>
            <value>
                <fullName>Rebate</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipName>CreditNoteJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note Line Item</label>
    <referenceTo>CreditNoteLineItem__c</referenceTo>
    <relationshipName>CreditNoteLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>InvoiceJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipName>InvoiceLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/globalRevenueRecognisedMethods_TEST.cls
@isTest(SeeAllData=true)
public class globalRevenueRecognisedMethods_TEST{
    
    public static testmethod void testRevenueRecognisedMethods(){
        
 		User user = [SELECT Id FROM User WHERE Profile.Name ='System Administrator' AND IsActive = TRUE LIMIT 1];
        
        Pricebook2 pbook = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
        
        //Insert Test Product 1            
        Product2 prod1 = new Product2( Name = 'Test Product 1',
                                       Description = 'Test Product 1 Description',
                                       Family = 'Software',
                                       Type__c = 'Software',
                                       ProductCode = 'TEST1'
                                     );
        insert prod1;
        
        PricebookEntry pbentry1 = new PricebookEntry( Pricebook2Id = pbook.Id,
                                                 Product2Id = prod1.Id,
                                                 IsActive = TRUE,
                                                 UseStandardPrice= FALSE,
                                                 UnitPrice = 0.00
                                               );
        insert pbentry1;
        
        //Insert Test Product 1            
        Product2 prod2 = new Product2( Name = 'Test Product 2',
                                       Description = 'Test Product 2 Description',
                                       Family = 'PLM',
                                       Type__c = 'Software',
                                       ProductCode = 'TEST2'
                                     );
        insert prod2;

        PricebookEntry pbentry2 = new PricebookEntry( Pricebook2Id = pbook.Id,
                                                 Product2Id = prod2.Id,
                                                 IsActive = TRUE,
                                                 UseStandardPrice= FALSE,
                                                 UnitPrice = 0.00
                                               );
        insert pbentry2;
        
        system.runAs(user){
            
            //Create a new Opportunity & Line Items
            Opportunity opp1 = new Opportunity();
            opp1.Name = 'Test Opportunity #1';
            opp1.Type = 'New Customer New Business';
            opp1.StageName = 'Order Processed';
            opp1.Probability = 100;
            opp1.CloseDate = System.Date.Today();
            opp1.Amount = 1500;
          	opp1.Customer_Order_Number__c = '1234';
            insert opp1;
               
            OpportunityLineItem opp1Li1 = new OpportunityLineItem();
            opp1Li1.OpportunityId = opp1.Id;
            opp1Li1.Quantity = 1;
            opp1Li1.UnitPrice = 500;
            opp1Li1.PriceBookEntryId = pbentry1.Id;
            insert opp1Li1;
            
            OpportunityLineItem opp1Li2 = new OpportunityLineItem();
            opp1Li2.OpportunityId = opp1.Id;
            opp1Li2.Quantity = 1;
            opp1Li2.UnitPrice = 500;
            opp1Li2.PriceBookEntryId = pbentry2.Id;
            insert opp1Li2;
            
            //Create a new Invoice & Line Items
            Invoice__c inv1 = new Invoice__c();
            inv1.Opportunity__c = opp1.Id;
            inv1.Company__c = 'SOLUTIONS';
            inv1.Date__c = System.Date.Today();
            insert inv1;
            
            InvoiceLineItem__c invLi1 = new InvoiceLineItem__c();
            invLi1.Invoice__c = inv1.Id;
            invLi1.Product__c = prod1.Id;
            invLi1.Name = prod1.Name;
            invLi1.BusinessType2__c = 'New';
            invLi1.Quantity__c = 1;
            invLi1.UnitPrice__c = 500;
            insert invLi1;
            
            InvoiceLineItem__c invLi2 = new InvoiceLineItem__c();
            invLi2.Invoice__c = inv1.Id;
            invLi2.Product__c = prod1.Id;
            invLi2.Name = prod1.Name;
            invLi2.BusinessType2__c = 'Renewal';
            invLi2.Quantity__c = 1;
            invLi2.UnitPrice__c = 500;
            insert invLi2;
            
            InvoiceLineItem__c invLi3 = new InvoiceLineItem__c();
            invLi3.Invoice__c = inv1.Id;
            invLi3.Product__c = prod2.Id;
            invLi3.Name = prod2.Name;
            invLi3.BusinessType2__c = 'New';
            invLi3.Quantity__c = 1;
            invLi3.UnitPrice__c = 500;
            insert invLi3;
            
            inv1.IsInvoice__c = TRUE;
            update inv1;
            
            //Create a new Credit Note & Line Items
            CreditNote__c crd1 = new CreditNote__c();
            crd1.Opportunity__c = opp1.Id;
            crd1.Company__c = 'SOLUTIONS';
            crd1.Date__c = System.Date.Today();
            insert crd1;
            
            CreditNoteLineItem__c crdLi1 = new CreditNoteLineItem__c();
            crdLi1.CreditNote__c = crd1.Id;
            crdLi1.Product__c = prod1.Id;
            crdLi1.Name = prod1.Name;
            crdLi1.BusinessType2__c = 'New';
            crdLi1.Quantity__c = 1;
            crdLi1.UnitPrice__c = 500;
            insert crdLi1;
            
            CreditNoteLineItem__c crdLi2 = new CreditNoteLineItem__c();
            crdLi2.CreditNote__c = crd1.Id;
            crdLi2.Product__c = prod1.Id;
            crdLi2.Name = prod1.Name;
            crdLi2.BusinessType2__c = 'Renewal';
            crdLi2.Quantity__c = 1;
            crdLi2.UnitPrice__c = 500;
            insert crdLi2;
            
            CreditNoteLineItem__c crdLi3 = new CreditNoteLineItem__c();
            crdLi3.CreditNote__c = crd1.Id;
            crdLi3.Product__c = prod2.Id;
            crdLi3.Name = prod2.Name;
            crdLi3.BusinessType2__c = 'New';
            crdLi3.Quantity__c = 1;
            crdLi3.UnitPrice__c = 500;
            insert crdLi3;
            
            crd1.IsCredited__c = TRUE;
            update crd1;
            
            //Refresh Opp Test
            globalRevenueRecognisedMethods.generateOppRevRec(opp1.Id);
            
            //Refresh Invoice Test
            globalRevenueRecognisedMethods.generateInvoiceRevRec(inv1.Id);
            
            //Refresh List of Opps Test
            List<Opportunity> opps = new List<Opportunity>([SELECT Id,
                                                                   (SELECT Id, 
                                                                           Ref__c,
                                                                           IsInvoice__c,
                                                                           Date__c,
                                                                           Type__c,
                                                                           Opportunity__r.Id,
                                                                           Opportunity__r.OwnerId 
                                                                    FROM OpportunityInvoices__r 
                                                                    WHERE IsInvoice__c = TRUE),
                                                                   (SELECT Id,
                                                                           Ref__c,
                                                                           IsCredited__c,
                                                                           Date__c,
                                                                           Type__c,
                                                                           Opportunity__r.Id,
                                                                           Opportunity__r.OwnerId 
                                                                    FROM OpportunityCreditNotes__r 
                                                                    WHERE IsCredited__c = TRUE),
                                                                   (SELECT Id 
                                                                    FROM RevenueRecognised__r)
                                                            FROM Opportunity 
                                                            WHERE Id =: opp1.Id]);
            
            globalRevenueRecognisedMethods.RevenueRecognisedMethods rev = new globalRevenueRecognisedMethods.RevenueRecognisedMethods();
            rev.generateRevenueRecognised(opps);
            
        }
        
    }

}