unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Commission Statement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/CommissionPayment__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CP{0000}</displayFormat>
        <label>Commission Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CommissionPayment__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <referenceTo>Commission__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Data Services</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>Solid Edge</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>AUTODESK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionRule__c/CommissionRule__c.object-meta.xml
<CustomObject>
    <label>Commission Rule</label>
    <nameField>
        <displayFormat>CMRL-{0}</displayFormat>
        <label>Commission Rule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CommissionRule__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionRule__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionRule__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Data Services</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>Solid Edge</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>Autodesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionRule__c/fields/RuleType__c.field-meta.xml
<CustomField>
    <fullName>RuleType__c</fullName>
    <label>Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionRule__c/fields/SalesPerson__c.field-meta.xml
<CustomField>
    <fullName>SalesPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CommissionRules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(CreditNote__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>ENERJYHUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( Opportunity__r.Division__c )</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(Invoice__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CASE(Division__c,
"PLM", "PLM",
"Solid Edge", "PLM",
"COMOS", "PLM",
"MPLM Software Development", "PLM",
"enerjyhub","ENERJYHUB",
"SOLUTIONS"
)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>The company division the opportunity falls under.</description>
    <inlineHelpText>The company division the opportunity falls under.</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data Services</fullName>
                <color>#78C953</color>
                <label>Data Services</label>
            </value>
            <value>
                <fullName>Dassault</fullName>
                <color>#A53711</color>
                <label>Dassault</label>
            </value>
            <value>
                <fullName>Consultants</fullName>
                <color>#993399</color>
                <label>Consultants</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Overhead</fullName>
            </value>
            <value>
                <fullName>EnerjyHub</fullName>
                <label>enerjyhub</label>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CommissionCompany__c.field-meta.xml
<CustomField>
    <fullName>CommissionCompany__c</fullName>
    <formula>CASE(ProductFamily__c,
"IT", "SOLUTIONS",
"Software", "SOLUTIONS",
"Data Services", "SOLUTIONS",
"enerjyhub", "ENERJYHUB",
"PLM", "PLM",
"Solid Edge", "PLM",
"SOLUTIONS")</formula>
    <label>Commission Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/globalCommissionMethods.cls
global class globalCommissionMethods{

    public without sharing class CommissionMethods {
        
        public void generateCommission(List<Revenue__c> revs){
            generateCommission(revs, null, null);
        }
        
        public void generateCommission(List<Revenue__c> revs, Integer theMonth){
            generateCommission(revs, theMonth, null);
        }
        
        public void generateCommission(List<Revenue__c> revs, Integer theMonth, Integer theYear){
                                    
            if(theMonth == null) {
                theMonth = System.Date.Today().Month();
            }
            if(theYear == null){
                theYear = System.Date.Today().Year();
            }
            
            Date theDate = Date.newInstance(theYear, theMonth, Date.daysInMonth(theYear, theMonth));
                                   
            Set<Id> ownerIds = new Set<Id>();
            
            //Build a Map of Sales People & Companies based on current Revenue__c records
            //i.e. commission statements that will be required
            Map<Id, Set<String>> ownerCompanyMap = new Map<Id, Set<String>>();
            for(Revenue__c rev : revs){
                ownerIds.add(rev.Owner.Id);
                
                if(ownerCompanyMap.get(rev.Owner.Id) == null){
                    ownerCompanyMap.put(rev.Owner.Id, new Set<String>{ rev.CommissionCompany__c });
                }
                else{
                    ownerCompanyMap.get(rev.Owner.Id).add(rev.CommissionCompany__c);
                }
            }
            
            //Build a Map of Sales People & Companies based on exisiting Commission__c records
            //i.e. commission statements that already exist and don't need to be created
            Map<Id, Map<String,Id>> ownerCompanyComMap = new Map<Id, Map<String,Id>>();
            for(Commission__c com : [SELECT Id, Owner.Id, Company__c FROM Commission__c WHERE CALENDAR_MONTH(Date__c) = :theMonth AND CALENDAR_YEAR(Date__c) = :theYear AND Owner.ID IN :ownerIds ]) {                
                if(ownerCompanyComMap.get(com.Owner.Id) == null){
                    ownerCompanyComMap.put(com.Owner.Id, new Map<String,Id>{ com.Company__c => com.Id });
                }
                else{
                    ownerCompanyComMap.get(com.Owner.Id).put(com.Company__c, com.Id);
                }
            }
            
            //Build a List of new Commission__c records to be created
            //i.e. commission statements that don't exists and need to be created
            List<Commission__c> newComs = new List<Commission__c>();
            
            for(Id ownerId : ownerCompanyMap.keySet()){
                if(!ownerCompanyComMap.keySet().contains(ownerId)){
                    for(String company : ownerCompanyMap.get(ownerId)){
                        Commission__c newCom = new Commission__c();
                        newCom.OwnerId = ownerId;
                        newCom.Date__c = theDate;
                        newcom.Company__c = company;
                        
                        newComs.Add(newCom);                        
                    }
                }
                else if(!ownerCompanyComMap.get(ownerId).keySet().containsAll(ownerCompanyMap.get(ownerId))){
                    for(String company : ownerCompanyMap.get(ownerId)){
                        if(!ownerCompanyComMap.get(ownerId).keySet().contains(company)){
                            Commission__c newCom = new Commission__c();
                            newCom.OwnerId = ownerId;
                            newCom.Date__c = theDate;
                            newcom.Company__c = company;
                            
                            newComs.Add(newCom);   
                        }
                    }
                }
            }
            
            if(!newComs.isEmpty()){
                insert newComs;
                
                for(Commission__c newCom : newComs){
                    if(ownerCompanyComMap.get(newCom.OwnerId) == null){
                        ownerCompanyComMap.put(newCom.OwnerId, new Map<String,Id>{ newCom.Company__c => newCom.Id });
                    }
                    else{
                        ownerCompanyComMap.get(newCom.OwnerId).put(newCom.Company__c, newCom.Id);
                    }
                }
            }
            
            //Build Currency Conversion Rate Map
            Map<String,Double> CurrencyConversionRateMap = new Map<String,Double>();
            for (CurrencyType CT:[SELECT Id, ConversionRate, IsoCode FROM CurrencyType]){
                CurrencyConversionRateMap.put(CT.IsoCode, CT.ConversionRate);
            }
                                    
            for(Revenue__c rev : revs){
                
                List<CommissionRule__c> allComRules = [SELECT Id, RuleType__c, SalesPerson__c, Division__c, CustomerType__c, BusinessType__c, ProductType__c, MinPercentTarget__c, Rate__c FROM CommissionRule__c 
                                                        WHERE Active__c = TRUE 
                                                        AND SalesPerson__c IN ( :rev.Owner.Id, '' )
                                                        AND Division__c IN ( :rev.ProductFamily__c , 'All' ) 
                                                        AND CustomerType__c IN ( :rev.Opportunity__r.Customer_Type__c, 'All' ) 
                                                        AND BusinessType__C IN ( :rev.BusinessType__c, 'All' ) 
                                                        AND ProductType__c IN ( :rev.ProductType__c, 'All' ) 
                                                        AND Product__r.Id IN ( :rev.InvoiceLineItem__r.Product__r.Id, :rev.CreditNoteLineItem__r.Product__r.Id, '' )
                                                        ORDER BY Priority__c ASC ];
                
                List<CommissionRule__c> productComRules = new List<CommissionRule__c>();
                List<CommissionRule__c> targetComRules = new List<CommissionRule__c>();
                List<CommissionRule__c> dealComRules = new List<CommissionRule__c>();
                
                for(CommissionRule__c comRule : allComRules){
                    if(comRule.RuleType__c == 'Product'){
                        productComRules.add(comRule);
                    }
                    else if(comRule.RuleType__c == 'Target' && comRule.SalesPerson__c == rev.Owner.Id){
                        targetComRules.add(comRule);
                    }
                    else if(comRule.RuleType__c == 'Deal'){
                        dealComRules.add(comRule);
                    }
                }
                if(targetComRules.isEmpty()){
                    for(CommissionRule__c comRule : allComRules){
                        if(comRule.RuleType__c == 'Target'){
                            targetComRules.add(comRule);
                        }
                    }
                }

                
                List<CommissionPayment__c> comPayments = new List<CommissionPayment__c>();
                
                if(allComRules.size()>0){
                    CommissionPayment__c comPayment = new CommissionPayment__c();
                    
                    comPayment.Commission__c = ownerCompanyComMap.get(rev.Owner.Id).get(rev.CommissionCompany__c);
                    comPayment.Opportunity__c = rev.Opportunity__c;
                    comPayment.Date__c = rev.Date__c;
                    comPayment.Division__c = rev.ProductFamily__c;
                    comPayment.CustomerType__c = rev.Opportunity__r.Customer_Type__c;
                    comPayment.BusinessType__c = rev.BusinessType__c;
                    comPayment.ProductType__c = rev.ProductType__c;
                    comPayment.CurrencyIsoCode = 'GBP';
                    if(rev.NetMargin__c != null){
                        comPayment.Margin__c = (rev.NetMargin__c / CurrencyConversionRateMap.get(rev.CurrencyIsoCode))*CurrencyConversionRateMap.get(comPayment.CurrencyIsoCode);
                    }
                    comPayment.RevenueID__c = rev.Id;
                    if(rev.Invoice__c != null)
                        comPayment.Invoice__c = rev.Invoice__c;
                    if(rev.CreditNote__c != null)
                        comPayment.CreditNote__c = rev.CreditNote__c;      
                                        
                    if(productComRules.size()>0){
                        CommissionRule__c productComRule = productComRules.get(0);
                        
                        comPayment.Rate__c = productComRule.Rate__c;
                        comPayment.CommissionRuleID__c = productComRule.Id;
                        comPayments.add(comPayment);
                    }
                    else if(targetComRules.size()>0 && rev.Opportunity__r.Target__c != null){
                        CommissionRule__c targetComRule = targetComRules.get(0);
                        
                        AggregateResult[] targetToDate = [SELECT Opportunity__r.Target__c,SUM(NetAmount__c),SUM(NetMargin__c) FROM Revenue__c WHERE Opportunity__r.Target__c = :rev.Opportunity__r.Target__c AND BusinessType__c = 'New' AND Date__c <= :rev.Date__c GROUP BY Opportunity__r.Target__c];
                        Double targetMarginToDate = 0;
                        Double targetPercentToDate = 0;
                        if(targetToDate.size()>0){
                            targetMarginToDate = Double.valueOf(targetToDate[0].get('expr1'));
                            targetPercentToDate = (targetMarginToDate / rev.Opportunity__r.Target__r.MarginTarget__c) * 100;
                        }
                        
                        //System.debug( 'targetPercentToDate: ' + rev.Date__c + ' = ' + targetPercentToDate );
                        
                        for(Integer i = 0; i < targetComRules.size(); i++){                        
                            //if(targetComRules.get(i).MinPercentTarget__c < rev.Opportunity__r.Target__r.PercentRecognisedMarginTargetAchieved__c)
                            //System.debug('MinPercentTarget__c: ' + targetComRules.get(i).MinPercentTarget__c);
                            if(targetComRules.get(i).MinPercentTarget__c < targetPercentToDate)
                                targetComRule = targetComRules.get(i);
                        }
                                                
                        comPayment.Rate__c = targetComRule.Rate__c;
                        comPayment.CommissionRuleID__c = targetComRule.Id;
                        comPayments.add(comPayment);
                    }
                    else if(dealComRules.size()>0){
                        CommissionRule__c dealComRule = dealComRules.get(0);
                        
                        comPayment.Rate__c = dealComRule.Rate__c;
                        comPayment.CommissionRuleID__c = dealComRule.Id;
                        comPayments.add(comPayment);
                    }
                }
                
                if(comPayments.size()>0){
                    insert comPayments;
                }
                
            }
            
        }
        
    }
    
    WebService static String[] generateOppCommission(String oppId){
        List<String> message = new List<String>();
        
        globalCommissionMethods.CommissionMethods com = new globalCommissionMethods.CommissionMethods();
        
        List<Revenue__c> oppRevs = [SELECT Id, 
                                           Owner.Id, 
                                           Date__c, 
                                           CommissionCompany__c, 
                                           ProductFamily__c, 
                                           BusinessType__c, 
                                           ProductType__c, 
                                           Invoice__c,
                                           InvoiceLineItem__r.Product__r.Id,
                                           CreditNote__c,
                                           CreditNoteLineItem__r.Product__r.Id,
                                           Opportunity__c, 
                                           Opportunity__r.Customer_Type__c, 
                                           Opportunity__r.Target__r.MarginTarget__c, 
                                           Opportunity__r.Target__r.PercentRecognisedMarginTargetAchieved__c, 
                                           NetMargin__c,
                                           CurrencyIsoCode
                                    FROM Revenue__c WHERE Opportunity__c =: oppId ];
                
        Set<ID> oppRevIds = new Set<ID>();
        for(Revenue__c oppRev : oppRevs){
            oppRevIds.add(oppRev.Id);
        }
        
        List<CommissionPayment__c> comPayments = [SELECT Id, RevenueID__c FROM CommissionPayment__c WHERE RevenueID__c IN :oppRevIds ];
        delete comPayments;
        
        com.generateCommission(oppRevs);
        
        return message;
    }
    
}