unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Commission Statement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/CreditNoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Note Line Item</label>
    <nameField>
        <label>Credit Note Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Note Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(CreditNote__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Credit Note Line Items</relationshipLabel>
    <relationshipName>CreditNoteLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNoteLineItem__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <formula>TEXT(Product__r.Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <formula>IF(ISBLANK(TEXT(BusinessType2__c)),
  IF(Product__r.NewBusiness__c,
    "New",
    CASE(Invoice__r.Opportunity__r.Type,
      "New Customer New Business", "New",
      "Existing Customer New Business", "New",
      "Existing Customer Maintenance Renewal", "Renewal",
      "Existing Customer Mixed Business", "Mixed",
      "Supplier Credit/Rebate", "Credit/Rebate",
      "Marketing Funding/Cost", "Marketing",
      "Other"
    )
  ),
  TEXT(BusinessType2__c)
)</formula>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>InvoiceLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvoiceLineItem__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <formula>TEXT(Product__r.Family)</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>CASE( Type ,
"New Customer New Business", "New",
"Existing Customer New Business", "Existing",
"Existing Customer Maintenance Renewal", "Existing",
"Existing Customer Mixed Business", "Existing",
"Other" )</formula>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognised</label>
    <nameField>
        <label>Revenue Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognised</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Revenue__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CommissionCompany__c.field-meta.xml
<CustomField>
    <fullName>CommissionCompany__c</fullName>
    <formula>CASE(ProductFamily__c,
"IT", "SOLUTIONS",
"Software", "SOLUTIONS",
"Data Services", "SOLUTIONS",
"enerjyhub", "ENERJYHUB",
"PLM", "PLM",
"Solid Edge", "PLM",
"SOLUTIONS")</formula>
    <label>Commission Company</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipName>CreditNoteJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/CreditNoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>CreditNoteLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note Line Item</label>
    <referenceTo>CreditNoteLineItem__c</referenceTo>
    <relationshipName>CreditNoteLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>InvoiceJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/InvoiceLineItem__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineItem__c</referenceTo>
    <relationshipName>InvoiceLineItemJournalEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/NetMargin__c.field-meta.xml
<CustomField>
    <fullName>NetMargin__c</fullName>
    <formula>CASE(Type__c,
"SI",  GrossMargin__c,
"SC", (0 - GrossMargin__c),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognised</relationshipLabel>
    <relationshipName>RevenueRecognised</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Revenue__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CommissionController.cls
public class CommissionController{
    
    private final Commission__c com;
    private static List<String> companies = new List<String>{
        'SOLUTIONS',
        'PLM'
    };
    private static Map<Integer, String> monthMap = new Map<Integer, String>{
        1 => 'January',
        2 => 'February',
        3 => 'March',
        4 => 'April',
        5 => 'May',
        6 => 'June',
        7 => 'July',
        8 => 'August',
        9 => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December'
    };
    private static List<Integer> years = new List<Integer>{
        System.Date.Today().Year()-1,
        System.Date.Today().Year(),
        System.Date.Today().Year()+1
    };
    
    

    public List<SelectOption> getCompanies() {
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption('','--Select Company--'));
        
        for(Integer i = 0; i < companies.size(); i++){
            options.add(new SelectOption(companies[i],companies[i]));
        }
        
        return options;    
    }
    
    public List<SelectOption> getMonths() {
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption('','--Select Month--'));
        
        for(Integer i = 1; i <= monthMap.size(); i++){
            options.add(new SelectOption(String.valueOf(i),monthMap.get(i)));
        }
        
        return options;    
    }
    
    public List<SelectOption> getYears(){
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption('','--Select Year--'));
        
        for(Integer i = 0; i < years.size(); i++){
            options.add(new SelectOption(String.valueOf(years[i]),String.valueOf(years[i])));
        }
        
        return options;    
    }
        
    public String selectedCompany {get; set;}
    public Integer selectedMonth {get; set;}
    public Integer selectedYear {get; set;}

    
    public PageReference generate() {
        PageReference pageRef;
        String[] result;
        
        //globalCommissionMethods.CommissionMethods com = new globalCommissionMethods.CommissionMethods();
        //List<Revenue__c> revs = [SELECT Id, Owner.Id, Date__c, CommissionCompany__c, ProductFamily__c, BusinessType__c, ProductType__c, Invoice__c, CreditNote__c, Opportunity__c, Opportunity__r.Customer_Type__c, Opportunity__r.Target__r.MarginTarget__c, Opportunity__r.Target__r.PercentRecognisedMarginTargetAchieved__c, NetMargin__c FROM Revenue__c WHERE CommissionCompany__c = :selectedCompany AND CALENDAR_MONTH(Date__c) = :selectedMonth ];
                        
        if ( selectedCompany != null && selectedMonth != null && selectedYear != null ) {
        
            String revQuery = 'SELECT Id, Owner.Id, Date__c, CommissionCompany__c, ProductFamily__c, BusinessType__c, ProductType__c, Invoice__c, InvoiceLineItem__r.Product__r.Id, CreditNote__c, CreditNoteLineItem__r.Product__r.Id, Opportunity__c, Opportunity__r.Customer_Type__c, Opportunity__r.Target__r.MarginTarget__c, Opportunity__r.Target__r.PercentRecognisedMarginTargetAchieved__c, NetMargin__c, CurrencyIsoCode FROM Revenue__c WHERE CommissionCompany__c = \'' + selectedCompany + '\' AND CALENDAR_MONTH(Date__c) = ' + selectedMonth + 'AND CALENDAR_YEAR(Date__c) = ' + selectedYear;

            globalCommissionBatch batchApex = new globalCommissionBatch(revQuery, selectedMonth, selectedYear);
            ID batchId = Database.executeBatch(batchApex, 50);
            
            pageRef = new PageReference ('/a0O');
        
            //if(!revs.IsEmpty()) {
                //com.generateCommission(revs, selectedMonth);              
                //pageRef = new PageReference ('/a0N');
            //}
        } else {
            //errors.add('You must select a company and month!');
            pageRef = null;
        }
        
        return pageRef;
    }

}