unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Commission Statement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CommissionPayment__c/CommissionPayment__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CP{0000}</displayFormat>
        <label>Commission Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CommissionPayment__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <referenceTo>Commission__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/CommissionPayment__c.field-meta.xml
<CustomField>
    <fullName>CommissionPayment__c</fullName>
    <formula>Margin__c * Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/CreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreditNote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Credit Note</label>
    <referenceTo>CreditNote__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Data Services</fullName>
            </value>
            <value>
                <fullName>PLM</fullName>
            </value>
            <value>
                <fullName>Solid Edge</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>AUTODESK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CommissionPayment__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CR{0000}</displayFormat>
        <label>Credit Note Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>OpportunityCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CreditNote__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>CreditNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( Opportunity__r.Division__c )</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>OpportunityInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Ref__c.field-meta.xml
<CustomField>
    <fullName>Ref__c</fullName>
    <formula>InvoiceNumber__c</formula>
    <label>Ref</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>The company division the opportunity falls under.</description>
    <inlineHelpText>The company division the opportunity falls under.</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data Services</fullName>
                <color>#78C953</color>
                <label>Data Services</label>
            </value>
            <value>
                <fullName>Dassault</fullName>
                <color>#A53711</color>
                <label>Dassault</label>
            </value>
            <value>
                <fullName>Consultants</fullName>
                <color>#993399</color>
                <label>Consultants</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Overhead</fullName>
            </value>
            <value>
                <fullName>EnerjyHub</fullName>
                <label>enerjyhub</label>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin (Legacy)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quote_Number_Revised__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number_Revised__c</fullName>
    <formula>Quote_Number__c&amp;LOWER(TEXT(Quotation_Revision_Tracker__c))</formula>
    <label>Quote Number (revised)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CommissionControllerExt.cls
public class CommissionControllerExt{

    private final Commission__c com;
    
    public Map<String, Map<String, CommissionPayment__c[]>> payments {get; set;}
    public Map<String, sObject> records {get; set;}
    public Map<String, AggregateResult> totals {get; set;}
    
    public CommissionControllerExt(ApexPages.StandardController stdController) {               
        this.com = (Commission__c)stdController.getRecord();
        
        loadData();
    }
    
    private void loadData(){
        payments = new Map<String, Map<String, CommissionPayment__c[]>>();
        records = new Map<String, sObject>();
        totals = new Map<String, AggregateResult>();
        
        for(CommissionPayment__c record : [SELECT Id, Name, Opportunity__c, Invoice__c, CreditNote__c, Date__c, Division__c, CustomerType__c, BusinessType__c, ProductType__c, Margin__c, Rate__c, CommissionPayment__c, Note__c FROM CommissionPayment__c WHERE Commission__r.Id =: com.Id ORDER BY Date__c ASC]){
            String opp = 'oppOther';
            if(record.Opportunity__c != null){
                opp = record.Opportunity__c;
            }
            
            String rev = 'revOther';
            if(record.Invoice__c != null){
                rev = record.Invoice__c;
            }
            else if(record.CreditNote__c != null){
                rev = record.CreditNote__c;
            }
                        
            if(!payments.containsKey(opp)){
                records.put(opp, null);
                payments.put(opp, new Map<String, CommissionPayment__c[]>());
            }
            if(!payments.get(opp).containsKey(rev)){
                records.put(rev, null);
                payments.get(opp).put(rev, new CommissionPayment__c[0]);
            }
            records.put(record.Id, record);
            payments.get(opp).get(rev).add(record);
        }
        
        for(AggregateResult sum : [SELECT Opportunity__c, SUM(Margin__c), SUM(CommissionPayment__c) FROM CommissionPayment__c WHERE Commission__r.Id =: com.Id GROUP BY Opportunity__c]){
            if(sum.get('Opportunity__c') != null){
                totals.put(String.valueOf(sum.get('Opportunity__c')), sum);
            }
            else {
                totals.put('oppOther', sum);
            }
        }
        
        for(AggregateResult sum : [SELECT Invoice__c, SUM(Margin__c), SUM(CommissionPayment__c) FROM CommissionPayment__c WHERE Commission__r.Id =: com.Id GROUP BY Invoice__c]){
            if(sum.get('Invoice__c') != null){
                totals.put(String.valueOf(sum.get('Invoice__c')), sum);
            }
            else {
                totals.put('revOther', sum);
            }
        }
        
        for(AggregateResult sum : [SELECT CreditNote__c, SUM(Margin__c), SUM(CommissionPayment__c) FROM CommissionPayment__c WHERE Commission__r.Id =: com.Id GROUP BY CreditNote__c]){
            if(sum.get('CreditNote__c') != null){
                totals.put(String.valueOf(sum.get('CreditNote__c')), sum);
            }
            else {
                totals.put('revOther', sum);
            }
        }
                        
        sObject oppOther = new Opportunity();
        oppOther.put('Name', 'Other');
        oppOther.put('CloseDate', null);        
        records.put('oppOther', oppOther);
        
        sObject revOther = new Invoice__c();
        records.put('revOther', revOther);  
        
        records.putAll([SELECT Id, Name, Quote_Number_Revised__c, CloseDate FROM Opportunity WHERE Id IN :records.KeySet()]);
        records.putAll([SELECT Id, Name, Ref__c, Date__c FROM Invoice__c WHERE Id IN :records.KeySet()]);
        records.putAll([SELECT Id, Name, Ref__c, Date__c FROM CreditNote__c WHERE Id IN :records.KeySet()]);
                
    }
    
}