unpackaged/main/default/objects/Opportunity/fields/Margin_Calc__c.field-meta.xml
<CustomField>
    <fullName>Margin_Calc__c</fullName>
    <label>Margin</label>
    <summarizedField>OpportunityLineItem.Margin__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Target__c/fields/MarginClosed__c.field-meta.xml
<CustomField>
    <fullName>MarginClosed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New Margin Closed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/MarginRecognised__c.field-meta.xml
<CustomField>
    <fullName>MarginRecognised__c</fullName>
    <defaultValue>0</defaultValue>
    <label>New Margin Recognised</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/MarginTarget__c.field-meta.xml
<CustomField>
    <fullName>MarginTarget__c</fullName>
    <label>New Margin Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Sales Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/SolutionsWallboard__c.field-meta.xml
<CustomField>
    <fullName>SolutionsWallboard__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select to make this user appear in the Solutions wallboard charts.</inlineHelpText>
    <label>Solutions Wallboard</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/intranet_Wallboards.cls
public class intranet_Wallboards {

    List<User> users = [SELECT Id, Name, FirstName, LastName FROM User WHERE SolutionsWallboard__c = TRUE];
    List<String> salesTeam = new List<String>();
    
    public intranet_Wallboards(){
        for (User u : users) {
            salesTeam.add(u.FirstName + ' ' + u.LastName);
        }
    }


    public List<AggregateResult> getResultsThisMonth() {
        List<AggregateResult> data = [SELECT Owner.Name owner, SUM(Amount) amount, SUM(Margin_Calc__c) margin FROM Opportunity WHERE CloseDate = THIS_MONTH AND IsWon = TRUE AND Owner.Name IN :salesTeam GROUP BY Owner.Name];
        return data;
    }
    
    public List<AggregateResult> getForecastThisMonth() {       
        List<AggregateResult> data = [SELECT Owner.Name owner, ForecastCategoryName probability, SUM(Amount) amount, SUM(Margin_Calc__c) margin FROM Opportunity WHERE CloseDate = THIS_MONTH AND IsWon = FALSE AND Owner.Name IN :salesTeam GROUP BY Owner.Name, ForecastCategoryName];
        return data;
    }
    
    public List<AggregateResult> getTargets() {
        String thisYear = String.valueOf(System.Date.Today().Year());
        
        List<AggregateResult> data = [SELECT Owner.Name owner, SUM(MarginTarget__c) target, SUM(MarginClosed__c) closed, SUM(MarginRecognised__c) invoiced FROM Target__c WHERE Year__c =: thisYear AND Owner.Name IN :salesTeam GROUP BY Owner.Name];  
        return data;
    }
    
    public List<AggregateResult> getActivitiesThisWeek() {       
        List<AggregateResult> data = [SELECT Owner.Name owner, COUNT(Id) total FROM Task WHERE Activity__c = 'Call' AND ActivityDate = THIS_WEEK AND IsClosed = TRUE AND Owner.Name IN :salesTeam GROUP BY Owner.Name];
        return data;
    }

}