unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>OpportunityPurchaseOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrder__c/fields/Ordered__c.field-meta.xml
<CustomField>
    <fullName>Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/PurchaseOrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItemProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PurchaseOrderLineItem__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/PurchaseOrderTriggerTests.cls
@isTest(seeAllData=true)
public class PurchaseOrderTriggerTests {
       
    public static testmethod void testPurchaseOrderTriggers(){
                        
        Product2 P = new Product2( Name = 'Test Product',
                                   Description = 'Test Product Description',
                                   Family = 'Test',
                                   ProductCode = 'TEST1234'
                                  );
        insert P;
                    
        User Usr = [Select id from User where Profile.Name ='Sales Support' and isActive = true limit 1];
        system.runAs(Usr){
        
            //Insert Test Account
            Account Acc = new Account( Name = 'Purchase Order Test Account' );
            insert Acc;
            
            //Insert Test Opportunity
            Opportunity Opp = new Opportunity( Name = 'Purchase Order Test Opp',
                                               AccountId = Acc.Id,
                                               Type = 'New Customer New Business',
                                               CloseDate = System.Date.today(),
                                               StageName = 'Order Received'
                                             );
            insert Opp;
            
            //Insert Test Purchase Order
            PurchaseOrder__c PO = new PurchaseOrder__c( Opportunity__c = Opp.id,
                                             Date__c = System.Date.today() );
            insert PO;
                                             
            //Insert Test Purchase Order Line Item #1
            PurchaseOrderLineItem__c poLI1 = new PurchaseOrderLineItem__c( PurchaseOrder__c = PO.Id,
                                                                Product__c = P.Id,
                                                                Name = P.Name + ' #1' );
            insert poLI1;
            
            //Insert Test Purchase Order Line Item #2
            PurchaseOrderLineItem__c poLI2 = new PurchaseOrderLineItem__c( PurchaseOrder__c = PO.Id,
                                                                Product__c = P.Id,
                                                                Name = P.Name + ' #2' );
            insert poLI2;
            
            //Change Purchase Order CurrencyIsoCode
            PO.CurrencyIsoCode = 'EUR';
            update PO;
            
            //Requery Purchase Order Line Items
            List<PurchaseOrderLineItem__c> poLIs = [SELECT Id, CurrencyIsoCode from PurchaseOrderLineItem__c WHERE PurchaseOrder__c =: PO.Id];
            
            //Check All Purchase Order Line Items have correct CurrencyIsoCode
            for( PurchaseOrderLineItem__c poLI : poLIs )
                System.AssertEquals( poLI.CurrencyIsoCode, 'EUR' );
            
            //Delete Purchase Order Line Item #1                                                    
            delete poLI1;
                                                                
            //Set Purchase Order to Ordered__c = TRUE
            PO.Ordered__c = TRUE;
            update PO;
            
            //Try to Delete Purchase Order Line Item #2
            try{
                //Delete Purchase Order Line Item #2                                                    
                delete poLI2;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot delete') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
            
            //Try to Undelete Purchase Order Line Item #1
            try{
                //Undelete Purchase Order Line Item #1                                                    
                undelete poLI1;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Cannot undelete') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
                        
        }   
 
    }
    
}