unpackaged/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProjectTask__c/ProjectTask__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProjectTask__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <externalId>true</externalId>
    <label>Activity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProjectTask__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProjectTask__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProjectTask__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Project is not active. You must select an active Project.</errorMessage>
        <filterItems>
            <field>Project__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProjectTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProjectTaskTriggerTests.cls
@isTest(seeAllData=true)
public class ProjectTaskTriggerTests {
       
    public static testmethod void testProjectTaskTriggerHandler(){
         
        //Define User  
        User User = [SELECT Id FROM User WHERE IsActive = TRUE LIMIT 1];
    
        //Insert Project
        Project__c Project = new Project__c( IsActive__c = TRUE );
        insert Project;
        
        //Insert Account
        Account Account = new Account( Name = 'Project Test Account' );
        insert Account;
        
        test.startTest();
                
        //Insert ProjectTask #1
        ProjectTask__c ProjectTask1 = new ProjectTask__c( Assigned__c = User.Id,
                                                          Project__c = Project.Id,
                                                          Status__c = 'In Progress',
                                                          Priority__c = 'High',
                                                          Name = 'Test Project Task 1' );
        insert ProjectTask1;
               
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
                
        //Find Task #1
        Task Task1 = [SELECT Id FROM Task WHERE ProjectTaskId__c =: ProjectTask1.Id LIMIT 1];
        //Delete Task #1
        delete Task1;
        
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
                
        //Update ProjectTask #1
        update ProjectTask1;
        
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
        
        //Update ProjectTask#1
        ProjectTask1.ActivityId__c = '';
        update ProjectTask1;
                
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
        
        //Update status to test Parent Project Chatter feed update
        ProjectTask1.Status__c = 'Completed';
        update ProjectTask1;
        
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
                
        //Delete ProjectTask #1
        delete ProjectTask1;
        
        //Prepare for next test
        ProjectTaskTriggerHandler.runOnce = false;
        
                
        //Undelete ProjectTask #1
        undelete ProjectTask1;
        
        test.stopTest(); 
                               
    }
    
    public static testmethod void testTaskTriggerHandler(){
    
        //Define User  
        User User = [SELECT Id FROM User WHERE IsActive = TRUE LIMIT 1];
    
        //Insert Project
        Project__c Project = new Project__c( IsActive__c = TRUE );
        insert Project;
        
        //Insert Account
        Account Account = new Account( Name = 'Project Test Account' );
        insert Account;
        
        //Insert Task #1
        Task Task1 = new Task( OwnerId = User.Id, WhatId = Project.Id, Subject = 'Test Task 1' );
        insert Task1;
                
        //Clear Id field
        Task1.ProjectTaskId__c = 'test';
        update Task1;
           
        //Delete Task #1
        delete Task1;
        
        //Undelete Task #1
        undelete Task1;
        
        //Insert Task #2 as Orphan
        Task Task2 = new Task();
        insert Task2;
        
        //Update Task #2
        //Add to Project
        Task2.WhatId = Project.Id;
        update Task2;
        //Update Task #2
        //update Task2;
        
        //Update Task #2
        //Remove from Project
        Task2.WhatId = Account.Id;
        update Task2;
    }
}